### ISSUE TITLE
Cannot access country ISO name in react simple maps.

### ISSUE THREAD

**Issue by mihir478** [zcreativelabs/react-simple-maps#1]
Not sure I fully explained what I want on twitter. I wanted a way to find the ISO country name while using react simple maps. I understand the 50m json has it. Can you easily expose the other properties on your geography object? Right now it only exposes the ISO numeric code (see screen shot), which I realize is better to support other locales, but no harm in exposing other properties too, with the ISO numeric ID. 

<img width="921" alt="screen shot 2017-06-05 at 12 00 54 pm" src="https://cloud.githubusercontent.com/assets/2001420/26791930/b017c81a-49e6-11e7-9f42-ed59c35dff24.png">

**Comment by mihir478** [comment]
If you don't think this makes sense with your API design, what are my alternatives? I would hate to maintain a json mappng object just for this.

**Comment by zimrick** [comment]
Not sure I fully understand the problem, but from what you are saying it seems like you want to access what is in `geography.properties`.

What is accessible there depends a little bit on how the topojson file is prepared, i.e. whether it has certain other properties specified on each feature.

Here's a full example:

```js
export default class Home extends Component {
  handleClick(geography) {
    // Inspect a specific country in the console by clicking on it...
    console.log(geography)
  }
  render() {
    return (
      <div>
        <ComposableMap style={{ width: "100%" }}>
          <ZoomableGroup>
            <Geographies geographyUrl="/static/world-50m.json">
              {(geographies, projection) => geographies.map(geography => {
                console.group("Geography")
                // Exposes geography with geography.id === iso codes etc.
                console.log("geography object: ", geography)
                // geography also has geography.properties
                console.log("Properties: ", geography.properties)
                console.groupEnd("Geography")
                return (
                  <Geography
                    key={ geography.id }
                    geography={ geography }
                    projection={ projection }
                    onClick={ this.handleClick }
                  />
                )
              })}
            </Geographies>
          </ZoomableGroup>
        </ComposableMap>
      </div>
    )
  }
}
```
<img width="1190" alt="screen shot 2017-06-05 at 19 32 07" src="https://cloud.githubusercontent.com/assets/7160099/26795386/bee1c852-4a25-11e7-9db9-ca5c64284cc8.png">

You can see in the screenshot that I can access the name of the country via `geography.properties.name`. With `world-50m.json` this should work, however there are other topojson files that don't have this information. A mapping object may be unavoidable there.

Again, not sure this is what you are after. Let me know if this helps.

**Comment by mihir478** [comment]
Thanks! I will use your topojson file.
