### ISSUE TITLE
Grouping Oceania regions together

### ISSUE THREAD

**Issue by dev637** [zcreativelabs/react-simple-maps#103]
Is there a way to isolate the map to only show the Oceania regions together so that they're aren't split off on both ends of the map? (BTW I should mention that I'm using the higher detailed 50m.json for the TopoJSON file)

**Comment by zimrick** [comment]
Hi @dev637,

You will have to use `projectionConfig` to rotate the projection, and then set the negative value of that rotation as your initial center offset.

Here is an example:
https://codesandbox.io/s/k3mx87kp95

I hope this helps.
