### ISSUE TITLE
how to center an image?

### ISSUE THREAD

**Issue by clarkevans** [zcreativelabs/react-simple-maps#108]
Hello @zimrick, thank you for writing React Simple Maps.  So, I'm have bootstrap problem with even the most basic thing: showing a particular TopoJSON file that is relatively small.  Between the "zoom" and the "center" parameters I find either the image shown is tiny... or off the screen.  If I manually provide a geographic center and then zoom, it still goes off the map.  So, I'm clearly not understanding some concept or doing something wrong.  I'd love a minimal, localized example that's not a world map.  

https://gist.github.com/clarkevans/ae9afd645234f617a744e2a5c5a101ba is a TopoJSON file of zipcodes in SanFrancisco's Peninsula. I'm trying to center this in a 300x300 div, so that to the right and below I could show information on each of the zipcodes as a user might click or hover over them. Using the defaults in the simplest example, at zoom=1.0, it's a speck of dust, but if I increase zoom, even when using a center of [-122.444, 37.760] it seems to be going off the map on me... which I don't understand.   

One final question; is there a way to use background image/tiling as they do in the gist above, to show the underlying geometry?  Thank you so much.  I appreciate any tips as I'm pretty much a novice here.  The examples are great, and they work, but, I just can't seem to get smaller geographies to work.

**Comment by clarkevans** [comment]
OK.  After all that work, it was a bounding div issue.   Thank you for the lovely library.

**Comment by zimrick** [comment]
Hi @clarkevans,

Thanks for giving react-simple-maps a try. Yeah, it can get a bit tricky if you have to zoom in very far. I have an example of a solution for your issue on codesandbox if it's still useful:

https://codesandbox.io/s/mq78884jyj

You can also configure the zoom via the `scale` option in `projectionConfig`. That way you don't have to deal with adapting `stroke` etc. for the high zoom factor. By using `rotate` in combination with `center`, you can also make sure that the projection is centered on SF.

RE the underlying tiles, it is currently not possible to do that. The focus with react-simple-maps is on SVG shapes only for now.

Hope this helps.

**Comment by clarkevans** [comment]
@zimrick Thanks, this works much better than what I did.   I have a suggestion, perhaps you could read the transform/translate section of the TopoJSON file and use this as the center?  There is also a scale there; do you have to invert it?  In this way, if someone doesn't manually set the center, it might automagically have a reasonable default.

**Comment by zimrick** [comment]
Thank you for the tip, will definitely look into this.
