### ISSUE TITLE
Example with Tooltip

### ISSUE THREAD

**Issue by kutyel** [zcreativelabs/react-simple-maps#11]
Hi! Awesome work btw!! Have been working in my own map for 1 month now with Datamaps, d3 and topojson and the experience hasn't been great so far... I am seriously considering switching to react-simple-maps but the only thing that prevents me is that I don't see clearly the Tooltip integration and it is a must for our business logic, I would highly appreciate a simple example in the docs showing how to do so, thanks in advance! 😄

**Comment by zimrick** [comment]
Hi, and thank you for giving `react-simple-maps` a try. 😃 

I just added an [example using `redux-tooltip`](https://github.com/zcreativelabs/react-simple-maps/tree/master/examples/with-redux-tooltip). I am sure there are plenty of other options out there. Basically, as long as you can trigger the tooltip via some kind of action it should work.

Hope this helps. Let me know if you run into any trouble with this.

**Comment by kutyel** [comment]
Awesome! That was fast! 🎉
