### ISSUE TITLE
Using Lines to connect two sets of Markers?

### ISSUE THREAD

**Issue by Unionindesign** [zcreativelabs/react-simple-maps#115]
First of all - thanks for creating this amazing library! This is more of a 'best-practice' question v. an issue...happy to supply some examples of my code of course! I am building a map that shows bookings...I am trying to show a marker with the activity that was booked, and a line connecting to a second marker for the billing address of the customer. I currently have two sets of markers rendering, would I use Lines to connect the two with start and end coordinates? Would there be a better way to do this? Thanks for any insights!

**Comment by zimrick** [comment]
Hi @Unionindesign,

Yep, probably best to use lines for this. It's an interesting use case. Would love to see examples of this.

**Comment by Unionindesign** [comment]
So I did get this working, and while we're still far from deployment I wanted to share some code in case anyone is trying to do the same thing. Thanks again for this great component library, and the speedy reply @zimrick!  A little pre-text...it seems the best way to to get an array of markers on the map projection of your choosing (per the docs) is to use the .map method, so I had originally split my data into two separate reports, two different js files, each with their own array of data to export into the map component...and then a third for the lines? It was getting messy! The current solution is to setup my data as one big array with nested 'client' and 'customer' objects, and to call on these in the Map component with dot notation.

Example:

export const bookingData = [
	{
		BookingId: 1234567,
		client: {
			coordinates: [-119.54251, 38.678],
			name: "the name of the client"
		},
		customer: {
			coordinates: [-119.1368, 46.2044],
			location: "where they are located, in case you want text/string etc",
		},
		CreatedAt: "2018-12-19 11:18:44.761717+00"
	},
....];
Now that you have your start coordinates (customer) and end coordinates (client), write a function to create a new object for your lines...mine looks like this:

export const lineData = bookingData.map(data => {
	const obj = {
		coordinates: {
			start: data.customer.coordinates,
			end: data.client.coordinates
		}
	};
	return obj;
});

And don't forget to export them at the bottom of the file of course!

export default {
	bookingData,
	lineData
};

Now, in your map component file...

Gotta import your data up top:

import { bookingData, lineData } from "/yourRelativeFilePath/filename.js"

and then add your two sets of markers, followed by your lines!

...
<Markers>
{bookingData.map((data, i) => (
	<Marker
		key={j}
		marker={data.client}
                style={{
				default: { fill: "#1B9750" },
				hover: { fill: "#FFFFFF" },
				pressed: { fill: "#0A6ECE" }
		}}>
	</Marker>
	))}
</Markers>

<Markers>
{bookingData.map((data, j) => (
	<Marker
		key={j}
		marker={data.customer}
                style={{
				default: { fill: "#1B9750" },
				hover: { fill: "#FFFFFF" },
				pressed: { fill: "#0A6ECE" }
		}}>
	</Marker>
	))}
</Markers>

<Lines>
	{lineData.map((line, i) => (
			<Line
				key={i}
					line={line}
					style={{
						default: { stroke: "#666" },
						hover: { stroke: "#999" },
						pressed: { stroke: "#000" }
					}}
				/>
			))}
</Lines>
								
Voila!
