### ISSUE TITLE
geographyPaths not working

### ISSUE THREAD

**Issue by j8seangel** [zcreativelabs/react-simple-maps#12]
Hi guys! First of all thanks for this awesome library! 

But the geographyPaths param is not working at all in the `Geographies` component when it is nested in a `ZoomableGroup` component because [here](https://github.com/zcreativelabs/react-simple-maps/blob/e07acccdd5b30a1c347f3070621c51d0545a92b7/src/utils.js#L44) you are passing the parent props that are empty to the new cloned element so it always takes the default value [].

So that is why I've created this [PR](https://github.com/zcreativelabs/react-simple-maps/pull/13) to try to fix it.

**Comment by zimrick** [comment]
Thx for flagging this. I merged your changes, and also added a fix to `componentWillReceiveProps`, which was not triggering properly. It should be possible to pass down your own geographyPaths now.

**Comment by j8seangel** [comment]
Awesome ! thank you very much !!
