### ISSUE TITLE
ComposableMap height and width props explained

### ISSUE THREAD

**Issue by alexlukelevy** [zcreativelabs/react-simple-maps#122]
When using a `ComposableGraph`, I was expecting to be able to set a width and height property and see the entire atlas drawn within those dimensions. Instead, I am seeing a cropped atlas if my width/height properties are not set large enough. I thought that given a zoom of 1, all the geographies should be visible no matter what size I choose to set the `ComposableGraph`.

```
<ComposableMap
  projectionConfig={{
    scale: 205,
    rotation: [-11, 0, 0],
  }}
  width={800}
  height={400}
>
  <ZoomableGroup disablePanning zoom={1}>
    <Geographies geography={`${process.env.PUBLIC_URL}/map.json`} disableOptimization>
      ...
    </Geographies>
  </ZoomableGroup>
</ComposableMap>
```
![atlas](https://user-images.githubusercontent.com/4173400/52167325-5c6bb280-2711-11e9-86c7-02ef5ab7d72a.png)

I am using the world-110m file [here](https://unpkg.com/visionscarto-world-atlas/world/110m.json)

**Comment by zimrick** [comment]
Hi @alexlukelevy,

If you set the scale to be 155 for this projection with your dimensions, you should be able to get a responsive map that shows all geographies (except for Antarctica).

```jsx
<ComposableMap
  projectionConfig={{
    scale: 155,
    rotation: [-11, 0, 0],
  }}
  width={800}
  height={400}
  style={{ width: "100%", height: "auto" }} 
>
  <ZoomableGroup disablePanning zoom={1}>
    <Geographies geography={`${process.env.PUBLIC_URL}/map.json`} disableOptimization>
      ...
    </Geographies>
  </ZoomableGroup>
</ComposableMap>
```

**Comment by alexlukelevy** [comment]
Thanks @zimrick! That does work nicely. Are you able to explain what `scale` does in this instance and how it interacts with `width` and `height`? I just copied the `scale` from one of the examples.

**Comment by alexlukelevy** [comment]
Also, what do the `height` and `width` properties really do, if this is just expanding responsively to the outer container? Is it simply setting the aspect ratio?

**Comment by bonbonio** [comment]
I agree it works confusingly; I would expect it to fit to the size of whatever containing sizes I set, without anything being cropped, it should also center in that container on both axis.

**Comment by d3dc** [comment]
Width and height is so confusing because it is the input to the [SVG's viewbox](https://css-tricks.com/scale-svg/):
```
viewBox={ viewBox ? viewBox : `0 0 ${width} ${height}` }
```

Its essentially setting the _internal_ resolution with `overflow: hidden` while the css styles and dom `width` and `height` (the same by default) distort the _internal_ rendering.

**Comment by bonbonio** [comment]
Rather than close it, would it not make more sense to make the maps work a little more logically?

**Comment by alexlukelevy** [comment]
Go for it.
