### ISSUE TITLE
Zoom on scrolling/wheel

### ISSUE THREAD

**Issue by babbel1005** [zcreativelabs/react-simple-maps#128]
Hi, 

is there a way to zoom by scrolling on the map ?
I tried to add the _scrolling event listener_ but it doesn't seem to work.
I can't find a proper way to do it.
Thank you

**Comment by AdriaanKuipers** [comment]
Here is very basic example, using the wheel-event. Based on [SO](https://stackoverflow.com/a/51276012)

Still searching for a 'zoom where mouse is' solution...

`import React, { Component } from "react";
import {
  ComposableMap,
  ZoomableGroup,
  Geographies,
  Geography
} from "react-simple-maps";

import world from "./world.json";

const wrapperStyles = {
  width: "100%",
  maxWidth: 980,
  margin: "0 auto"
};

class Map extends Component {
  constructor(props) {
    super(props);
    this.state = {
      bypass: false,
      zoom: 1,
      strokeWidth: 0.5
    };

    this.handleWheel = this.handleWheel.bind(this);
  }

  handleWheel(event) {
    console.log("scroll detected");
    console.log(event.deltaY);

    if (event.deltaY > 0) {
      this.setState({
        zoom: this.state.zoom / 1.1,
        strokeWidth: this.state.strokeWidth * 1.1
      });
    }
    if (event.deltaY < 0) {
      this.setState({
        zoom: this.state.zoom * 1.1,
        strokeWidth: this.state.strokeWidth / 1.1
      });
    }
  }

  render() {
    return (
      <div style={wrapperStyles}>
        <ComposableMap
          projectionConfig={{
            scale: 205,
            rotation: [-11, 0, 0]
          }}
          width={980}
          height={551}
          style={{
            width: "100%",
            height: "auto"
          }}
        >
          <ZoomableGroup center={[0, 20]} zoom={this.state.zoom}>
            <Geographies geography={world}>
              {(geographies, projection) =>
                geographies.map(
                  (geography, i) =>
                    geography.id !== "ATA" && (
                      <Geography
                        key={i}
                        onWheel={this.handleWheel}
                        geography={geography}
                        projection={projection}
                        style={{
                          default: {
                            fill: "#ECEFF1",
                            stroke: "#607D8B",
                            strokeWidth: 0.75,
                            outline: "none"
                          },
                          hover: {
                            fill: "#607D8B",
                            stroke: "#607D8B",
                            strokeWidth: 0.75,
                            outline: "none"
                          },
                          pressed: {
                            fill: "#FF5722",
                            stroke: "#607D8B",
                            strokeWidth: 0.75,
                            outline: "none"
                          }
                        }}
                      />
                    )
                )
              }
            </Geographies>
          </ZoomableGroup>
        </ComposableMap>
      </div>
    );
  }
}

export default Map;
`

**Comment by Unionindesign** [comment]
Thanks! I've been wondering about this!

**Comment by mlnor27** [comment]
Thanks for the solution, it works perfectly !!

However, i have the scrolling event propagating up to the body scroll.
I tried calling `stopPropagation` and `preventDefault` on the event but it doesn't make the trick.

Anyone else having the same issue ?

**Comment by AdriaanKuipers** [comment]
event.preventDefault() should do the trick. check [this](https://codesandbox.io/s/218wpw3okn) for a live example.

Note that the oceans aren't geography objects in the example, so scrolling there won't work...

```js
handleWheel(event) {
    event.preventDefault();
    console.log("scroll detected");
    console.log(event.deltaY);

    if (event.deltaY > 0) {
      this.setState({
        zoom: this.state.zoom / 1.1
      });
    }
    if (event.deltaY < 0) {
      this.setState({
        zoom: this.state.zoom * 1.1
      });
    }
  }
```

**Comment by mlnor27** [comment]
l already tried this and it still keeps scrolling the entire page... :/

**Comment by AdriaanKuipers** [comment]
If you make a [codesandbox](codesandbox.io), I can have a look

**Comment by zimrick** [comment]
Closing this. With v2, this should work much better now, since it uses d3-zoom under the hood.

**Comment by chrisk8er** [comment]
@zimrick can you show some ref or tutorial to implement it? thanks

**Comment by zimrick** [comment]
Here is the zoomable group example using v2:
https://codesandbox.io/s/zoomablegroup-8ithq

**Comment by lucianthorr** [comment]
This might still be an issue on Safari. If I take the codesandbox example above and copy/paste a few maps inside a single <div></div>, you'll see that the screen scrolls as the map zooms on Safari.  Seems fine on Chrome however.

**Comment by JanMisker** [comment]
> This might still be an issue on Safari. If I take the codesandbox example above and copy/paste a few maps inside a single `<div></div>`, you'll see that the screen scrolls as the map zooms on Safari. Seems fine on Chrome however.

I see the same behavior. On Chrome and Firefox the WheelEvent is captured to zoom on the map only, but on Safari (desktop) the WheelEvent zooms the map but also scrolls the page. preventDefault and stopPropagation don't solve it.

**Comment by sasha-kolisetsky-nl** [comment]
Hey guys!

**Comment by sasha-kolisetsky-nl** [comment]
How to add ctrl + scroll for zooming map as it works for googleMaps?

**Comment by davletovalmir** [comment]
@sasha-kolisetsky-nl, I was able to hack it with the following code:

```tsx
  // ... beginning of the component

  const zoomableGroupDom = useRef<SVGElement>(null);

  useEffect(() => {
    const geographyEl = zoomableGroupDom.current; // points to <g> with geography elements
    const emptyZoneEl = geographyEl?.previousElementSibling as SVGElement; // points to <rect> with empty space on the map
    if (!geographyEl || !emptyZoneEl) return;

    function handleZoom(event: WheelEvent) {
      if (!(event.metaKey || event.ctrlKey)) {
        event.stopPropagation();
      }
    }

    geographyEl.addEventListener("wheel", handleZoom, { passive: false });
    emptyZoneEl.addEventListener("wheel", handleZoom, { passive: false });

    return () => {
      geographyEl.removeEventListener("wheel", handleZoom);
      emptyZoneEl.removeEventListener("wheel", handleZoom);
    };
  }, []);

  // ... rest of the component

  return (
    // ... beginning
    <ZoomableGroup ref={zoomableGroupDom}>
      // ... children
    </ZoomableGroup>
    // ... end
  );
```

Few things to note:
1. It may break if DOM structure will change in future, as it's just a hack
2. Typings, for some reason, think that `ref` is not supported by the `ZoomableGroup` component. I checked the JS implementation, `ref` is there, and it works. I fixed it by hacking the component type as follows:

```ts
const ZoomableGroup = ZoomableGroupOrig as React.FC<
  ZoomableGroupProps & { ref: RefObject<SVGElement> }
>;
```

I hope it helps!
