### ISSUE TITLE
Marker positions incorrect

### ISSUE THREAD

**Issue by Stuart88** [zcreativelabs/react-simple-maps#133]
Not sure what I've done wrong here. 

Map markers won't render at the correct lat/long positions. 

Code looks like this:

                                 <Markers>
                                    {
                                        this.state.Destinations.map((city, i) => (
                                            <Marker key={i} >
                                                <circle 
                                                    cx={city.long}
                                                    cy={city.lat}
                                                    r={10}
                                                    style={{
                                                        stroke: "#FF5722",
                                                        strokeWidth: 3,
                                                        opacity: 0.9,
                                                    }}
                                                />
                                                <text
                                                    textAnchor="middle"
                                                    y={city.lat - 25}
                                                    x={city.long}
                                                    style={{
                                                        fontFamily: "Roboto, sans-serif",
                                                        fill: "#607D8B",
                                                    }}
                                                >
                                                    {city.name}
                                                </text>
                                            </Marker>
                                        ))
                                    }
                                </Markers>

and my map marker data looks like this:

![Capture](https://user-images.githubusercontent.com/23031872/54757342-f84f7000-4c24-11e9-894c-eefd394312b9.PNG)

The code is based on the examples here: https://www.react-simple-maps.io/simple-markers

I've gone through the zooming/panning example and have no problem with that.  Currently if I click the navigation buttons to go to my markers, the map navigates to the correct place (e.g. clicking Shanghai focuses the map over Shanghai, based on its lat/long position)

However, the _marker_ for Shanghai (and every other location) is wrong. See below.

![Capture](https://user-images.githubusercontent.com/23031872/54757055-69425800-4c24-11e9-95a8-cfffdd929f02.PNG)

I presume I've missed something somewhere. Any help much appreciated, thanks.

**Comment by zimrick** [comment]
Hi @Stuart88,

You seem to be using the longitude and latitude to set `cx` and `cy` directly on the circle.
Check out the `Marker` docs:
https://github.com/zcreativelabs/react-simple-maps#Marker-component

You can use the `marker` prop on your `Marker` component and then pass the longitude and latitude as coordinates. This will use the projection under the hood to calculate the offsets for you.

For Shanghai this would be:

```jsx
<Marker marker={{ coordinates: [ 121.4747, 31.25516 ] }}>
  <circle cx={0} cy={0} r={10} />
</Marker>
```

**Comment by Stuart88** [comment]
Fixed it, thanks!

I forgot to mention, I originally left out that marker prop because it stopped existing after I installed @types for react-simple-maps, so it just gave a red underline and wouldn't render. Oddly enough, the marker prop is back now after firing things up this morning. I probably just made a mistake somewhere.

Problem solved, cheers, and thanks for pointing me to the docs
