### ISSUE TITLE
 Unexpected end of JSON input while parsing near '..."package-preamble":"0' on install

### ISSUE THREAD

**Issue by saulojoab** [zcreativelabs/react-simple-maps#145]
I'm simply trying to install the dependency on my React project by running
`npm install --save react-simple-maps`

And this is what I'm getting:
![image](https://user-images.githubusercontent.com/37988252/62401090-0c529900-b558-11e9-9fdc-b61f0e8829a5.png)
```bat
npm ERR! Unexpected end of JSON input while parsing near '..."package-preamble":"0'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Saulo Joab\AppData\Roaming\npm-cache\_logs\2019-08-02T21_57_31_284Z-debug.log
```

I have no idea what's causing this, I'm using windows 10.

**Comment by zimrick** [comment]
Hi @saulojoab,
I'm not sure this has anything to do with react-simple-maps. Maybe this can help with your problem:
https://github.com/vuejs-templates/webpack/issues/990?

**Comment by saulojoab** [comment]
Running `npm cache clean --force` fixed it. That was weird.

Thanks for the help!
