### ISSUE TITLE
Tooltip integration with react-tooltip

### ISSUE THREAD

**Issue by kutyel** [zcreativelabs/react-simple-maps#15]
Hi!

I finally decided to switch to your awesome library but found a little problem: I use some state to toggle a class `active` to some countries which applies *the same color* as the `hover` fill but when you hover over a sidebar of continents, each country belonging to that continent should highlight, my state is working correctly, but the map does not re-render, any ideas?

Thanks in advance!

**Comment by zimrick** [comment]
This probably has to do with the default optimisation. Check the `<Geographies />` component and make sure that you set the `disableOptimisation` prop.

https://github.com/zcreativelabs/react-simple-maps#Geographies-component

Note that performance optimisation was improved (56794b89e3220852ab56270b98f759d92df16ab5) and can be handled using a `cacheId` as of version 0.7.0.

Let me know if that solves it for you.

**Comment by kutyel** [comment]
Great! This worked, only after using `disableOptimization={true}`! Thanks 🎉 🎉 🎉 

I have a few other issues (maybe its my problem or not):

1. For some reason, I can move the whole map while clicking on it and holding, the `ZoomableGroup` translate function seems to be affected by the hold-click movement, I checked your examples and none of the maps move, but mine does 😕 
2. I am using the `50m.json` with no projection at all, and the last piece of Russia appears cut and close to Alaska in the West side of the Map, the cut is not nice and it is clear to the eye, it doesn't appear in any of your examples and that bothers me as well 😱 
3. And the last and worse of all, is that we are using [react-tooltip](https://github.com/wwayne/react-tooltip) in our library, and can't really switch to `redux-tooltip`, this library needs to have a `data-tip` and `data-for={str}` props to show up, and I tried adding those to the `<Geography>` component and they don't work, I think is due to the fact that extra props don't get passed into the dom (like with `{...props}`).

If you could help me with this I would really appreciate it, and I would be able to finish my work on the Map component for our library (its being a month now, so I am quite tired of the map 😜 )

Thanks in advance for any help you can give me!

**Comment by kutyel** [comment]
Another stupid question: is there a way to map **real** latitude and longitude data to the svg data? They don't seem to be related and I have to guess the location of some cities :worried:

**Comment by zimrick** [comment]
RE: 1
Yes, panning is enabled by default. You can easily disable that on the `<ZoomableGroup />` component using the `disablePanning` prop.
https://github.com/zcreativelabs/react-simple-maps#ZoomableGroup-component

RE: 2
By default any projection will be displayed with a split Russia. This is a common problem. You can use the `projectionConfig` prop on the `<ComposableMap />` component to change the `rotation` of the projection ([-10,0,0] should do the trick).
https://github.com/zcreativelabs/react-simple-maps#ComposableMap-component

RE: 3
I will have a look at react-tooltip. Will post another example once I figure this out.

Hehe, I can see how this can get frustrating after a while ;)

**Comment by kutyel** [comment]
I can't say enough thank you for all this @zimrick! <3

**Comment by zimrick** [comment]
Regarding the cities, taking coordinates from Google should work. Do you have a specific example of where this didn't work? Note that Google and d3 use a different order of longitude and latitude (at least to my knowledge), so that can lead to quite some confusion.

You should be able to use proper coordinates with Markers, like so:

```js
<Marker marker={{ name: "Tokyo", coordinates: [139.6917,35.6895] }} >
  <circle cx={0} cy={0} r={6} />
<Marker>
```
For an example, check:
https://github.com/zcreativelabs/react-simple-maps/tree/master/examples/bubbles-map

Note that if you are using anything but circles, the center point of the marker may get skewed. SVG places circles based on the middle of the cirlce, but rectangles use the upper left corner as a reference point, so the square would be to the South East of the actual coordinate. In that case you can offset the square by half its size. This is more of an SVG issue though...

No worries, glad you are giving this a try, happy mapping!

**Comment by kutyel** [comment]
Damn I feel so stupid, its the typical problem: I was taking the coords and you copy them like this: `[lat,lng]`, and maybe the map needs them like this: `[lng,lat]` 😅  (or the other way round, thanks!)

**Comment by zimrick** [comment]
No worries, it happens quite often. ;)

**Comment by kutyel** [comment]
BTW: I just wanted to share my happiness so I think this is a good enough place 😄 .

My implementation of the map **before** `react-simple-maps`:

<img width="690" alt="before" src="https://user-images.githubusercontent.com/5127501/29666443-9c0f2fee-88d8-11e7-97a9-f1a73a81b49b.png">

My implementation **after** `react-simple-maps`:

<img width="870" alt="after" src="https://user-images.githubusercontent.com/5127501/29666453-aa444e5a-88d8-11e7-85a4-5a702b8f56cc.png">

🎉 🎉 🎉

**Comment by zimrick** [comment]
Awesome!!! Feel free to share a link to the final result once it's out.

**Comment by kutyel** [comment]
Sure thing! 👌

**Comment by kutyel** [comment]
Hi! Is this reopened because of the **react-tooltip** thing? Should I rename the Issue? Thanks in advance! 😄

**Comment by zimrick** [comment]
Yup, just preparing an example.

**Comment by kutyel** [comment]
Great! Awesome work @zimrick, it is a pleasure to work in OSS with people like you, please, let me know if there is any beginner issue or something minor from the library that I could fix because I am very willing to help to this project and love the work from @zcreativelabs 👍

**Comment by zimrick** [comment]
Just thought I'd post this here, since we left the react-tooltip issue unresolved. In version 0.8.0 (9417dd8432be92e62634879639e7e8ee69e579b8) you should now be able to pass properties to the path in the `<Geography />` component. Check out the new [react-tooltip example](https://github.com/zcreativelabs/react-simple-maps/tree/master/examples/with-react-tooltip) for how to make this work properly. There is a little trick with `componentDidMount` and `ReactTooltip.rebuild()` that you have to put in there as well.

Note, there are still some quirks regarding the placement of the tooltip when using `effect="solid"` (it places it at the top left corner of the geography), so for now I would suggest using `effect="float"`. Putting tooltips on the svg elements within the `<Marker />` component worked out of the box when I tried it last time, so that should not be an issue if you need it.

Hope this resolves the issue for you.

**Comment by kutyel** [comment]
Awesome! Great work and thank you very much! Will give it a try very soon :)

**Comment by kutyel** [comment]
Hi again @zimrick! I have been trying your example and it does funny things: sometimes works and sometimes it doesn't, either way, as soon as we change anything related to the tooltip (our case: `place="top"`) it does not show at all 😕  Besides, we have to display custom information inside the tooltip (just a div with some `span`s and `h2`s) and that is why we have to use the `data-id data-for="724"` API of the Tooltip, which seems to *not* work at all with the map either. Would be really appreciative if you could take a look :)

**Comment by mihir478** [comment]
I ended up implementing my own tooltip because tooltip libs were giving me a lot of trouble as well. 

`geographyJSX = (<Geography
          key={idx}
          geography={geography}
          projection={projection}
          style={mapStyle}
          onMouseMove={(_this, e) => this.showTooltip(tooltipData, e)}
          onMouseLeave={() => this.hideTooltip()}
        />);

showTooltip(tooltipData, event) {
    const { location, value, valueColor } = tooltipData;

    if (location && !Number.isNaN(value)) {
      this.setState({ tooltip: {
        location,
        value: 1000, // your value
        valueColor,
        show: true,
        x: event.clientX + this.tooltipOffset.x,
        y: event.clientY + this.tooltipOffset.y,
      } });
    } else {
      this.hideTooltip();
    }
  }

  hideTooltip() {
    this.setState({ tooltip: { location: null, value: null, show: false } });
  }`

**Comment by zimrick** [comment]
If you are interested in custom html content for each tooltip, [`wsdm-tooltip`](https://www.npmjs.com/package/wsdm-tooltip) does a pretty good job, and it's lean. Here's how it would work with `react-simple-maps`. Note that the html inside the tooltip is regular html, rather than jsx.

```js
import React, { Component } from "react"
import tooltip from "wsdm-tooltip"

import {
  ComposableMap,
  ZoomableGroup,
  Geographies,
  Geography,
} from "react-simple-maps"

class Map extends Component {
  constructor() {
    super()
    this.handleMouseMove = this.handleMouseMove.bind(this)
    this.handleMouseLeave = this.handleMouseLeave.bind(this)
  }
  componentDidMount() {
    this.tip = tooltip()
    this.tip.create()
  }
  handleMouseMove(geography, evt) {
    this.tip.show(`
      <div class="tooltip-inner">
        ${geography.id}
      </div>
    `)
    this.tip.position({ pageX: evt.pageX, pageY: evt.pageY })
  }
  handleMouseLeave() {
    this.tip.hide()
  }
  render() {
    return (
      <div>
        <ComposableMap width={980} height={500}>
          <ZoomableGroup>
            <Geographies geographyUrl="/static/world-50m.json">
              {(geographies, projection) =>
                geographies.map((geography, i) =>
                  <Geography
                    key={i}
                    geography={geography}
                    projection={projection}
                    onMouseMove={this.handleMouseMove}
                    onMouseLeave={this.handleMouseLeave}
                    style={{
                      default: { fill: "#EEE", outline: "none" },
                      hover: { fill: "#DDD", outline: "none" },
                      pressed: { fill: "#AAA", outline: "none" },
                    }}
                  />
              )}
            </Geographies>
            <Graticule />
          </ZoomableGroup>
        </ComposableMap>
      </div>
    )
  }
}
```

For the css, you can work with something like this:

```css
.wsdm-tooltip {
  display: none;
  padding: 0.5rem 1rem;
  background: rgba(255, 255, 255, 0.95);
  border-radius: 3px;
  pointer-events: none;
  text-align: center;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.2);
  z-index: 1000;
}
.wsdm-tooltip:after {
  content: "";
  position: absolute;
  width: 0;
  height: 0;
  top: 100%;
  left: 50%;
  margin-left: -0.5rem;
  border-left: 0.5rem solid transparent;
  border-right: 0.5rem solid transparent;
  border-top: 0.5rem solid rgba(255, 255, 255, 0.95);
}
```

Hope this is useful.

**Comment by kutyel** [comment]
Hey! I hadn't seen those replies before I am sorry! Huge thanks to @zimrick and @mihir478 as well, I ended up making a div and creating a very simple tooltip that shows up in the `onMouseEnter`/`onMouseLeave` events and that is all, thanks again!

BTW: I am going to talk about this library in an upcoming [conf](http://reactalicante.es/) to praise and evangelise about this awesome project and its creators! 😍

**Comment by zimrick** [comment]
Awesome!
