### ISSUE TITLE
componentWillMount deprecated

### ISSUE THREAD

**Issue by Sventenhaaf** [zcreativelabs/react-simple-maps#150]
Great package, thanks so much for sharing!

I'm getting warnings that the `componentWillMount` method is deprecated and that I should use `UNSAFE_componentWillMount`. Could you version bump your version of React or the dependencies that are outdated that cause this warning?

Thanks!

**Comment by imaan** [comment]
@Sventenhaaf Did you find a solution to this? Having the same issue
