### ISSUE TITLE
Rotate not working on latest Beta 

### ISSUE THREAD

**Issue by jpedroribeiro** [zcreativelabs/react-simple-maps#159]
If you pick the **Author's** example: https://codesandbox.io/s/101vl9jl and update it to use the latest package version (`"react-simple-maps": "1.0.0-beta.0"`) you will see that the `rotate` prop is ignored - this is made clear by observing how Russia is "split".

Is there any other way of applying rotate to the map or is this a feature missing in the latest beta?

**Comment by zimrick** [comment]
Hi @jpedroribeiro,

Yup, there are a couple of minor changes in naming with the new version. Among other things we switched to `rotate` to reflect the underlying d3-geo api. Rotate should properly alter the map the way you want.

Apart from that though, this older example also uses an older version of react without hooks, so you have to update that as well. We are in the process of tracking down the older examples and fixing the issues. In the meantime, there is a new basic map example, which you may find more useful:

https://codesandbox.io/s/basic-map-wvlol

Hope this helps.

**Comment by jpedroribeiro** [comment]
You know what, I was using `rotation` instead of `rotate` 😅
My bad, thanks for the feedback and for the excellent library ;)

**Comment by zimrick** [comment]
No worries, sorry for the confusion. I know these bigger version switches can be a pain...
