### ISSUE TITLE
taiwan should be same coloar as China's instead of grey

### ISSUE THREAD

**Issue by amehito** [zcreativelabs/react-simple-maps#160]

**Comment by Erroler** [comment]
Why should it? It's not part of China.

**Comment by mooncakelmn** [comment]
> Why should it? It's not part of China.

Please don't judge if you don't know the truth. The truth is Taiwan is always one part of China.

**Comment by mooncakelmn** [comment]
Guys, let's not create duplicated tickets and focus on https://github.com/zcreativelabs/react-simple-maps/issues/19

**Comment by amehito** [comment]
Sorry, I was not familiar with GitHub at that time
