### ISSUE TITLE
Most basic example won't work on latest version

### ISSUE THREAD

**Issue by Amiryy** [zcreativelabs/react-simple-maps#161]
Hello,
I wanna use `react-simple-maps` with Typescript.
Since types are defined for 0.12+ versions only I am forced to use the latest versions of the library (0.12.1). Trying to do so results in an error, presumably because the render props passed by `Geographies` has changed. 
Trying to console.log those props returned an empty array.

Please see this example: 
https://codesandbox.io/s/basic-map-s4cdv?fontsize=14&hidenavigation=1&theme=dark

Note that the only difference from the [original example](https://www.react-simple-maps.io/docs/getting-started/) is the version specified in package.json.

I couldn't find any explanation about the latest version and how to use it on the website/docs.

Thank you.

**Comment by zimrick** [comment]
Hi @Amiryy,

The documentation as well as all the old examples are still available in the repo under the [`v0.12.x` branch](https://github.com/zcreativelabs/react-simple-maps/tree/v0.12.x).

There is one additional change in the API from v0.12 to v1, and that is that v0.12 returns the geographies, and v1 returns an object, which contains geographies, projection, and path. so the difference is that in v1 you can use destructuring to get the geographies, and in v0.12 you just get the geographies directly. Note that v0.12 also does not have an `rsmKey` for the geographies, so you will have to make a unique id (based off iso code, or something else unique for every country).

```jsx
// v0.12
<Geographies geography={geoUrl}>
  {(geographies) =>
    geographies.map(geo => <Geography key={geo.id} geography={geo} />)
  }
</Geographies>

// v1
<Geographies geography={geoUrl}>
  {({ geographies }) =>
    geographies.map(geo => <Geography key={geo.rsmKey} geography={geo} />)
  }
</Geographies>
```

Hope this helps.

**Comment by Amiryy** [comment]
Thanks @zimrick.
I decided to use the same version as the examples do but creating my own type declaration - at least until the current one gets updated to reflect v1+.

here is what I've added so far:
```
export interface GeographyObject {
  rsmKey: string,
  geometry: {
    coordinates: Array<Array<number>>
  }
  type: string;
  svgPath: string;
  type: string;
  properties: {
    CONTINENT: string;
    ABBREV: string;
    CONTINENT: string;
    FORMAL_EN: string;
    GDP_MD_EST: number;
    GDP_YEAR: number;
    ISO_A2: string;
    ISO_A3: string;
    NAME: string;
    NAME_LONG: string;
    POP_EST: number;
    POP_RANK: number;
    POP_YEAR: number;
    REGION_UN: string;
    SUBREGION: string;
  }
}

export interface GeographiesRenderProps {
  geographies: Array<GeographyObject>,
  projection: GeoProjection,
  path: object,
}
```

including this modification to `Geographies` child render props:
```
export interface GeographiesProps {
  disableOptimization?: boolean;
  geography?: string | { [key: string]: any } | string[];
  children?: (props: GeographiesRenderProps) => void;
}
```

**Comment by zimrick** [comment]
That's cool @Amiryy,

If you are using v1, the `disableOptimization` prop is no longer in use. It was a bit of a confusing feature of rsm that has been solved differently in v1, so the prop has been retired.

**Comment by illepic** [comment]
@Amiryy how are you utilizing these custom types? Is this in a `d.ts` file within your project? Thanks for putting in the work to figure out the v1 types!

**Comment by Amiryy** [comment]
@illepic Hey, you're welcome.
I create an `index.d.ts` file under a `myTypes/react-simple-maps/` directory.
`myTypes` is used as an extending type declarations folder in my project, this is where I keep my custom-defined type declarations and you can call it whatever you like.
Then I add it to my `ts.config` so Typescript will know about it:
```
//ts.config
...
"compilerOptions": {
...
    "paths": {
...
      "*": ["./myTypes/*"]
    },
...
```
