### ISSUE TITLE
Cannot read property '0' of null. When Projection is used with ZoomableGroup (Demo included)

### ISSUE THREAD

**Issue by juanpasolano** [zcreativelabs/react-simple-maps#162]
Hi,
It seems that using a projection with a `<ZoomableGroup>` throws `Cannot read property '0' of null`.
In this example https://codesandbox.io/s/usa-state-labels-map-1icyl you can see that removing the projection makes the map work.

Thank you very much for this super nice package.

**Comment by zimrick** [comment]
Hi @juanpasolano,

That error seems to come from the missing `center` prop on the ZoomableGroup component. Try adding a valid center (i.e. within the bounds of the Albers USA projection). Something like `[-96,38]` should work quite well...

That should fix the problem.
Cheers

**Comment by juanpasolano** [comment]
You are amazing! Thank you so very much!
