### ISSUE TITLE
How can i disable the outline and clicking on the map?

### ISSUE THREAD

**Issue by Usama-Aslam** [zcreativelabs/react-simple-maps#166]
I have tried **diabled** but its not working. I don't want the user to be able to click on the map and get the outline. Is there any solution to stop this?

![image](https://user-images.githubusercontent.com/36229784/71304469-1252f480-23e9-11ea-8b00-b419be6f159e.png)

 <ComposableMap
      projectionConfig={{
        scale: 200
      }}
      className="mapMainComponent"
      style={{ marginLeft: 0 }}
      disabled
    >

      <Geographies geography={geoUrl} disabled>
        {({ geographies }) =>
          geographies
            .filter(
              d =>
                d.properties.REGION_UN === "Americas" ||
                d.properties.REGION_UN === "Europe" ||
                d.properties.REGION_UN === "Asia"
            )
            .map(geo => (
              <Geography
                key={geo.rsmKey}
                geography={geo}
                fill="#EAEAEC"
                stroke="#D6D6DA"
                disabled
              />
            ))
        }
      </Geographies>
      {markers.map(({ name, coordinates, markerOffset, color }) => (
        <Marker key={name} coordinates={coordinates}>
          <circle r={10} fill={color} stroke="#fff" strokeWidth={2} />
          <text
            textAnchor="middle"
            y={markerOffset}
            style={{ fontFamily: "system-ui", fill: color, fontSize: "30px" }}
          >
            {name}
          </text>
        </Marker>
      ))}
    </ComposableMap>

**Comment by zimrick** [comment]
Hi @Usama-Aslam,
You can remove the outline by using `style` and setting `outline: "none"` on all states. If the geographies on your map will not be interactive, it is also best to set `tabIndex={-1}` on the `Geography`.

```jsx
<Geography
  key={geo.rsmKey}
  geography={geo}
  fill="#EAEAEC"
  stroke="#D6D6DA"
  style={{
    default: { outline: "none" },
    hover: { outline: "none" },
    pressed: { outline: "none" },
  }}
/>
```

**Comment by pguardiario** [comment]
Thumbs up and this should be the default in the codesandboxes because I don't imagine many people want those boxes.
