### ISSUE TITLE
Need a way to reset the backdrop rect

### ISSUE THREAD

**Issue by jinqiupeter** [zcreativelabs/react-simple-maps#17]
Thanks for this awesome library!

If I zoom in the map and pan it around, is it possible to reset the backdrop rect to it's original position? 
I tried center but it didnot work

This is my code:
```
<Motion
                    defaultStyle={{
                        zoom: 1,
                        x: thisStatus.center[0],
                        y: thisStatus.center[1],
                    }}
                    style={{
                        zoom: spring(thisStatus.zoom, {stiffness: 210, damping: 20}),
                        x: spring(thisStatus.center[0], {stiffness: 210, damping: 20}),
                        y: spring(thisStatus.center[1], {stiffness: 210, damping: 20}),
                    }}
                >
                    {({zoom,x,y}) => (
                        <ComposableMap
                            width={width}
                            height={height}
                            style={{
                                width: "100%",
                                height: "auto",
                            }}
                            projection={this.projection}
                        >
                            <ZoomableGroup disablePanning={thisStatus.zoom === 1} center={[x,y]} zoom={zoom}>
```

**Comment by zimrick** [comment]
Just to clarify the process. This happens when you:

1. Zoom in (without first panning)
2. pan around
3. Zoom out
4. Try to reset the center

Is that about right? If yes, then this is an issue we are currently working on solving. There is currently a problem with how the center gets set from the outside or from within the map component.

**Comment by jinqiupeter** [comment]
Thanks for reply.

I managed to get what I wanted: just pass a different center so that ZoomableGroup will reset panning because the center is different. Here is what I did for your reference, I changed my reset button handler from:

`resetClick={() => this.setState({zoom: 1, center: [0,20]})}`
to
```
resetClick={() =>
	this.setState({
		zoom: 1,
		center: [
			this.state.center[0],
			// return a new center so ZoomableGroup will reset panning
			this.state.center[1] % 2 === 0 ? this.state.center[1] + 1 : this.state.center[1] - 1
							]
	})
}
```
