### ISSUE TITLE
Broken example for ZoomableGroup

### ISSUE THREAD

**Issue by sarovin** [zcreativelabs/react-simple-maps#179]
Hi, there is an error in this example => https://codesandbox.io/s/zoom-controls-iwo3f?from-embed linked in the doc.

The function onZoomEnd return two params: event and position.

EXAMPLE:
```
function handleZoomEnd(position) {
    setZoom(position.zoom);
  }
```

FIXED: 
```
function handleZoomEnd(event, position) {
    setZoom(position.zoom);
  }
```

**Comment by zimrick** [comment]
Hi @sarovin,

Thanks for flagging. With v2 out, this should now work much better:
https://codesandbox.io/s/zoom-controls-iwo3f
