### ISSUE TITLE
Bug: map not removing hover class onMouseOver

### ISSUE THREAD

**Issue by kutyel** [zcreativelabs/react-simple-maps#18]
Hi again!

I managed to make my own implementation of a tooltip with `styled-components` and was able to position it like so:

```js
handleMove = ({ id }, e) => {
  const tooltip = this.state.countries.find(({ code }) => code === id);
    if (tooltip) {
      const x = e.clientX;
      const y = e.clientY + 25;
      this.setState({ x, y, tooltip });
   }
};

handleLeave = () => this.setState({ tooltip: null });
```

The weird behaviour started when, since the moment I implemented the `onMouseMove` method, the map adds a class on hover to each **path**, but after leaving such path, the class does not get removed. So I end up having all the map with the hover color (which is darker) once I hovered over the whole map.

Is this a bug, something I am doing wrong? Is there an easy way without having to *hack* the map of removing that class?

Thanks in advance! ❤️

**Comment by zimrick** [comment]
Ok, managed to replicate the issue. Definitely something wrong there. Looking into it.

**Comment by zimrick** [comment]
Found the problem. Thx for flagging this. This is an error that happened in the last update to 0.8.0. The events were being improperly transferred, which resulted in an event override in some cases, hence the weird hover behaviour. Will push a fix to this in a bit.

**Comment by zimrick** [comment]
Should be fixed in v0.8.1 (619fc1f0c1d961cf1636c4633f85456ab2b177df).

**Comment by kutyel** [comment]
It works! Huge thanks 🎉

**Comment by kutyel** [comment]
BTW this is a preview of the finished map, looks awesome! Huge thanks @zimrick and @zcreativelabs!!! 🎉 

![map-finished](https://user-images.githubusercontent.com/5127501/29918624-590a8ed2-8e46-11e7-8bac-21050ded4b09.png)

It will be one of the main features in the next release of the [TMView](https://www.tmdn.org/tmview/welcome) website (any time beginning next year), an importante website for trademarks of the EU. The map right know is prepared for being themable and has a huge zoom effect over every continent! 🗺
