### ISSUE TITLE
disablePanning + disableZooming not working

### ISSUE THREAD

**Issue by vitordino** [zcreativelabs/react-simple-maps#191]
i need a map that is centered to a point, and can’t zoom or pan, how should i do it?

simple reproduction: https://codesandbox.io/s/rsm-disable-panning-zooming-rzvtk

**Comment by zimrick** [comment]
If you don't need zooming or panning, you can always just omit the ZoomableGroup component, and instead use the projectionConfig to set `rotation` or `center`.

Check out this example:
https://codesandbox.io/s/map-with-custom-projection-config-5rwh6?file=/src/MapChart.js

**Comment by vitordino** [comment]
wow, thanks for the quick response <3

i’ll try it here, closing for now

**Comment by Harshit369** [comment]
@zimrick how can we handle a use-case where we can disable zoom on scroll and provide user two action buttons to zoom-in or zoom-out?. I was thinking to leverage disable zoom there and manually updating zoom on click or something like that.

**Comment by Midnightgb** [comment]
Hi @Harshit369  I just found your old comment — did you manage to find a clean way to disable scroll zoom and also disable map dragging/panning, while still allowing zoom in/out manually through buttons?

I’m trying to implement something similar and wondering if you came up with a good solution back then.
