### ISSUE TITLE
Singapore is missing from your world map.

### ISSUE THREAD

**Issue by f0rfun** [zcreativelabs/react-simple-maps#196]
Is the map supposed to be complete? Or is it a work in progress? How many other countries were left out?

**Comment by ikarasz** [comment]
@f0rfun the library's task is to draw a map based on a topojson. The topojson is up to you, you can create your own with any countries, regions whatever.

**Comment by f0rfun** [comment]
I see! Thanks! :D

**Comment by phatlamhd** [comment]
Hi @f0rfun @ikarasz could you share me the `arcs` of Singapore to be able to draw by this library 
I've tried to find out coordinates but cannot use by this library
Thanks

**Comment by f0rfun** [comment]
Hey @phatlamhd, you can check out my repo here for your reference. I haven't touched the code in awhile but I remember I swapped out the topojson for something else entirely.

**Comment by phatlamhd** [comment]
Thanks @f0rfun I can draw now
