### ISSUE TITLE
Want a way to update the geographies object, using disableOptimization for now but it kills performance.

### ISSUE THREAD

**Issue by mihir478** [zcreativelabs/react-simple-maps#2]
<img width="1018" alt="screen shot 2017-06-06 at 5 27 40 pm" src="https://user-images.githubusercontent.com/2001420/26852882-c7b74d4a-4add-11e7-8fed-a9d0941f9b57.png">
<img width="1017" alt="screen shot 2017-06-06 at 5 27 28 pm" src="https://user-images.githubusercontent.com/2001420/26852881-c7b6a61a-4add-11e7-89a2-a1b3e32c1e6b.png">

I have the use case of building 4 flavors of the map (2 shown here). I do want the maps to re-render on different data values, although the length of the data is the same. For e.g. when I click on different tabs, the parent component passes in different data values to my map component, but the length is the same as it is keyed by countries. The issue is that you have a guard preventing the geographies from re-rendering if the length of the data is the same. The length of my data is the same, but the values are different (which determine the fill shade). 

I used `disableOptimization` to force a re-render, but the panning performance suffers badly because of this. 

Additionally, what about animating bubbles and shapes to grow and fade-in respectively? Do you support that?

**Comment by zimrick** [comment]
This is one of those things that I would like to improve about the library. Like you said, without the guard you get bad panning and animation performance, but as long as the guard is on, you can't update the geographies. There is currently a workaround for this though. You can disable optimization only when you switch the dataset and then use the setState callback to switch the optimization back on.

Here's an example to illustrate how to get around the issue:

```js
import React, { Component } from "react"
import { scaleLinear } from "d3-scale"
import {
  ComposableMap,
  ZoomableGroup,
  Geographies,
  Geography,
  Markers,
  Marker,
} from "react-simple-maps"

const subregions = {
  "Northern Europe": "#081d58",
  "Southern Europe": "#253494",
  "Eastern Europe": "#225ea8",
  "Western Europe": "#1d91c0",
  "Western Asia": "#800026",
  "Central Asia": "#bd0026",
  "Eastern Asia": "#e31a1c",
  "Southern Asia": "#fc4e2a",
  "South-Eastern Asia": "#fd8d3c",
  "Australia and New Zealand": "#feb24c",
  "Melanesia": "#fed976",
  "Micronesia": "#ffeda0",
  "Polynesia": "#ffffcc",
  "Northern Africa": "#41b6c4",
  "Eastern Africa": "#7fcdbb",
  "Western Africa": "#c7e9b4",
  "Middle Africa": "#edf8b1",
  "Southern Africa": "#ffffd9",
  "Northern America": "#004529",
  "Central America": "#006837",
  "Caribbean": "#238443",
  "South America": "#41ab5d",
  "Seven seas (open ocean)": "#78c679",
  "Antarctica": "#addd8e",
}

const popScale = scaleLinear()
  .domain([0,100000000,1400000000])
  .range(["#BDE5E6","#00B3C6","#0C2544"])

export default class ChoroplethMap extends Component {
  constructor() {
    super()

    this.state = {
      optimizationDisabled: false,
      populationData: true,
    }

    this.switchDataset = this.switchDataset.bind(this)
  }
  switchDataset() {
    this.setState({
      optimizationDisabled: true,
      populationData: !this.state.populationData,
    }, () => {
      this.setState({
        optimizationDisabled: false,
      })
    })
  }
  render() {
    return (
      <div>
        <button onClick={ this.switchDataset }>
          { "Switch dataset" }
        </button>
        <ComposableMap style={{ width: "100%" }}>
          <ZoomableGroup center={[0,0]}>
            <Geographies
                geographyUrl={ "/static/world-50m-with-data.json" }
                disableOptimization={ this.state.optimizationDisabled }
              >
              {(geographies, projection) => geographies.map(geography => (
                <Geography
                  key={ geography.properties.adm0_a3 }
                  geography={ geography }
                  projection={ projection }
                  style={{
                    default: {
                      fill: this.state.populationData ? popScale(geography.properties.pop_est) : subregions[geography.properties.subregion],
                    }
                  }}
                />
              ))}
            </Geographies>
          </ZoomableGroup>
        </ComposableMap>
      </div>
    )
  }
}
```

Hope this makes sense. Let me know if you run into any problems with this.

**Comment by mihir478** [comment]
That's a really good workaround. I'm glad to find out setState accepts a callback.

**Comment by zimrick** [comment]
There are a couple of approaches to how to handle animation with react-simple-maps. I am still preparing a proper example for this, but here are some thoughts.

You can add basic zoom animation using react-motion by extending the zoom example from the readme:

```js
import { Motion, spring } from "react-motion"

...

<Motion defaultStyle={{ zoom: 1 }} style={{ zoom: spring(this.state.zoom) }}>
  {({zoom}) => (
    <ComposableMap style={{ width: "100%" }}>
      <ZoomableGroup zoom={ zoom }>
        <Geographies geographyUrl={ "/static/world-110m.json" }>
          {(geographies, projection) => geographies.map((geography, i) => (
            <Geography
              key={ `geography-${geography.id}-${i}` }
              geography={ geography }
              projection={ projection }
              style={{
                default: { fill: "#ddd" }
              }}
            />
          ))}
        </Geographies>
      </ZoomableGroup>
    </ComposableMap>
  )}
</Motion>

...

```

You can also add basic css transitions on the individual geographies via the style prop to get a nice little animation when updating the choropleth.

```js
...
<Geography
    key={ `geography-${geography.id}-${i}` }
    geography={ geography }
    projection={ projection }
    style={{
        default: {
            fill: "#ddd",
            transition: "fill 0.5s",
        }
    }}
/>
...
```

For the initial growing bubbles you could use react-motion.

```js
...
<Marker marker={{ coordinates: [0,0] }}>
    <Motion defaultStyle={{ scale: 0 }} style={{ scale: spring(1) }}>
        {({scale}) => (
            <circle cx={0} cy={0} r={scale * 20} fill="#000" />
        )}
    </Motion>
</Marker>
...
```

**Comment by mihir478** [comment]
@zimrick The above works well in some cases. While I try to get to the bottom of the issue, I suspect one of the causes is that it does not work on newly created DOM elements. Do you have a fix that maybe uses requestAnimationFrame to make the above solutions work?
