### ISSUE TITLE
onZoomEnd method is deprecated in v2

### ISSUE THREAD

**Issue by mkarajohn** [zcreativelabs/react-simple-maps#201]
I just upgraded to v2 and stumbled upon this issue, in a `ZoomableGroup` component:

`Unknown event handler property `onZoomEnd`. It will be ignored.`

While the types still show 

```
    onZoomStart?: (event: any, position: Position) => void;
    onZoomEnd?: (event: any, position: Position) => void;
```

it seems these methods are deprecated, judging by the fact that even the [official example](https://codesandbox.io/s/zoom-controls-iwo3f?from-embed=&file=/src/MapChart.js:744-757) uses `onMoveEnd` now, instead of `onZoomeEnd` as [mentioned](https://www.react-simple-maps.io/docs/zoomable-group/) in the docs (see Events section).

Since types are maintained in a whole different repo, should I at least open a PR updating the docs here?

**Comment by zimrick** [comment]
Thanks for flagging, updated the docs accordingly.
