### ISSUE TITLE
Examples on your website

### ISSUE THREAD

**Issue by dfyz011** [zcreativelabs/react-simple-maps#206]
Examples on your website https://www.react-simple-maps.io/examples are not working.
All examples have the same error.
<img width="1680" alt="Снимок экрана 2020-06-01 в 14 16 42" src="https://user-images.githubusercontent.com/45315708/83394857-c0d87800-a412-11ea-9730-ab6f74724a00.png">

**Comment by zimrick** [comment]
I can't seem to recreate this issue locally. I pushed a fix with version 2.1.2 to avoid this error on codesandbox, but the zoom is now disabled on codesandbox. Locally everything should work fine... Will be looking into this further.
