### ISSUE TITLE
Map is broken / filled in, despite using valid GeoJSON

### ISSUE THREAD

**Issue by jthistle** [zcreativelabs/react-simple-maps#209]
I'm creating a map in the style of the example at https://www.react-simple-maps.io/docs/geographies/. The only difference is that instead of a link to a TopoJSON file, I am using an array of GeoJSON MultiPolygons. The exact object I'm passing to `Geographies` can be [found in this gist](https://gist.github.com/jthistle/35b5d1c9845fdbb98fcb22b03fa28900). If you want to see what it looks like, [here it is formatted as a FeatureCollection](https://gist.github.com/jthistle/bf030dacecefa094f97e9f100e0c5768). It's valid, because GitHub manages to display it fine. 

What I get looks like this:

![Screenshot from 2020-06-05 23-41-06](https://user-images.githubusercontent.com/8274049/83927853-10f26a00-a786-11ea-8d49-5d629f9deb7c.png)

The stroke I'm using is `red`, and the fill is `black`.

What I expect to happen is something like the GitHub display linked above, but this isn't what happens. Any help is appreciated!

**Comment by zimrick** [comment]
Hi @jthistle,
I see a couple of issues here. Not sure how github managed to render this geojson file, but I can't manage to get it to work with react simple maps. I took a closer look at the geojson file and noticed that the borders have a lot of overlap, so you get a lot of extra information in there that you don't really need, which is the reason the file is also around 8mb. You will run into issues with a file this size.

I looked around and found a fairly nice version of counties and unitary authorities from: http://geoportal.statistics.gov.uk/datasets/6638c31a8e9842f98a037748f72258ed_0?geometry=-20.581%2C52.262%2C13.169%2C56.723

This should have the same information that you need for your map, but after I simplified and transformed it into topojson it weighs in at around 160kb. Here's a working example in codesandbox:
https://codesandbox.io/s/uk-subnational-map-w0jc2?file=/src/MapChart.js

**Comment by jthistle** [comment]
That's interesting, because that's exactly where I got the GeoJSON from in the first place.

**Comment by jthistle** [comment]
It's not a size issue, I think, because when I use just a single one of the MultiPolygons rather than just the whole file, I still get a completely black map...

**Comment by zimrick** [comment]
Hmm, that's interesting. I tried it one more time with your geojson (although I reduced the size a bit for testing purposes). The same bug appeared, but when I make the fill transparent, I can see the shapes properly. Check it out here:
https://codesandbox.io/s/dazzling-mcclintock-r2yly?file=/src/MapChart.js

It seems that there's something off with the formatting so one of the shapes covers the entire globe. If you zoom out the scale you can see that the fill would cover the entire sphere.

**Comment by zimrick** [comment]
Oh ok, I found this:
https://stackoverflow.com/questions/49311001/d3-js-osm-geojson-black-rectangle

I believe this is your issue.

> The issue is the winding order of the coordinates (see this block). Most tools/utilities/libraries/validators don't really care about winding order because they treat geoJSON as containing Cartesian coordinates. Not so with D3 - D3 uses ellipsoidal math - benefits of this is include being able to cross the antimeridian easily and being able to select an inverted polygon.

> The consequence of using ellipsoidal coordinates is the wrong winding order will create a feature of everything on the planet that is not your target (inverted polygon). Your polygons actually contain a combination of both winding orders.

You could use the solution suggested if you want to use this geojson file in specific. Alternatively you could see if the file I posted above works for you. I would take another look at the geojson either way to avoid the duplicate borders, which add a lot of weight to your geojson file at the moment.

Hope this helps.

**Comment by jthistle** [comment]
Ah, that helps a lot, thank you! I think I'm going to end up converting GeoJSON to TopoJSON server-side and sending that over, then using it for the map, since that'll help loading times as well as making it work. Thanks again.

**Comment by jthistle** [comment]
Hmmm, what did you use to fix the winding and transform it into the TopoJSON file you posted above?

**Comment by jthistle** [comment]
Don't worry, managed to fix it! My pipeline ended up looking like:

- start with ONS-provided GeoJSON
- rewind the bounds with `@mapbox/geojson-rewind` (setting `clockwise` to `true` - important)
- convert to topojson with `topojson-server`
- simplify with `topojson-simplify` (which expects smaller values for the weight threshold than I expected!)
- reformat for database storage

Thanks again for all your help! :)

![uk_good](https://user-images.githubusercontent.com/8274049/84012058-e44d7680-a96e-11ea-8301-c8624fa58c0b.png)

**Comment by jonsherrard** [comment]
@jthistle you are my absolute hero for documenting this.

**Comment by jthistle** [comment]
@jonsherrard glad I could help :)
