### ISSUE TITLE
Disable panning but not zooming

### ISSUE THREAD

**Issue by Sapkotaanish** [zcreativelabs/react-simple-maps#211]
I want to allow zooming of maps but want to disable panning. I have tried a lot to achieve this and even looked for d3 solutions but cannot figure it out. How can this be done?

**Comment by zimrick** [comment]
Hi @Sapkotaanish,

It depends a little bit on the exact behaviour you are looking for. Either you can use the `translateExtent` option for `d3-zoom`, thereby constraining the map to a bounding box. This would mean that panning is disabled when the map is zoomed out, but once you zoom to a specific area, you can also pan around.

Here's an example:
https://codesandbox.io/s/react-simple-maps-constrained-panning-3tr6z?file=/src/MapChart.js:405-438

If you really want to prevent all panning, then you can also tap into the `filterZoomEvent` option and filter out all mouse events. Here's an example of this:
https://codesandbox.io/s/react-simple-maps-prevent-panning-n97ik?file=/src/MapChart.js
