### ISSUE TITLE
Roughjs support

### ISSUE THREAD

**Issue by willb335** [zcreativelabs/react-simple-maps#222]
Can anyone provide an example of a map with roughjs or react roughjs support?  I have tried using React Rough, https://github.com/ooade/react-rough, with limited success.  

Thank you for the great library

**Comment by zimrick** [comment]
Hi @willb335,

I did this a while back:
https://codesandbox.io/s/react-simple-maps-rough-js-u3ple

Let me know if it helps you

**Comment by willb335** [comment]
Wow, very cool.  Thank you
