### ISSUE TITLE
Annotation is rendering behind map

### ISSUE THREAD

**Issue by willb335** [zcreativelabs/react-simple-maps#223]
The annotation line is rendering behind the map, any help is appreciated.  

<img width="735" alt="boston" src="https://user-images.githubusercontent.com/10157307/88729232-5c2f5600-d101-11ea-9550-d59f4dae9b8d.png">

https://codesandbox.io/s/peaceful-thunder-jk7dj?file=/src/App.js

**Comment by zimrick** [comment]
Hi @willb335,
It seems that you are rendering the annotations (line + text) in the same iteration as the geographies, based on the geography data. That's perfectly fine to do in react-simple-maps. The only issue is that this will put certain annotations under the geographies that are rendered later. If you want the annotations to be above the geographies altogether, you need to map over the geographies data twice, and render the annotations after (i.e. further down in the code than) the geographies. It would roughly look something like this:

```jsx
<Geographies>
  {({ geographies }) => {
    return (
      <React.Fragment>
        {geographies.map(geo =>
          <Geography key={geo.rsmKey} geography={geo} />
        )}
        {geographies.map(geo => {
          return // annotations go here...
        })}
      </React.Fragment>
    )
  }
</Geographies>
```

Let me know if this works for you.

**Comment by willb335** [comment]
<img width="911" alt="Screen Shot 2020-07-29 at 5 52 55 AM" src="https://user-images.githubusercontent.com/10157307/88785924-d42c6900-d15f-11ea-9485-a4ec39f4e5ac.png">

Worked great, thank you!
