### ISSUE TITLE
How to achieve ZoomableGlobe under current version?

### ISSUE THREAD

**Issue by zezhehh** [zcreativelabs/react-simple-maps#230]
I notice that there is a API called ZoomableGlobe which supports zoom and rotate in the map. But it disappears in the master branch. Is there an easy way to implement it?

**Comment by victormpa** [comment]
Took a while to find, but it was commited here https://github.com/zcreativelabs/react-simple-maps/commit/51178d041dbb1e7e77b0d6e1d8b8d2c25d7f570f#diff-4486c9691fe14ecc7db27addcb8692dad0d6e618a036c1027bbac182ba488166
