### ISSUE TITLE
static map files

### ISSUE THREAD

**Issue by cquex** [zcreativelabs/react-simple-maps#234]
Hi, 
Im having an issue creating my map. I create my json file on https://mapshaper.org/ with the country that i want: 

![image](https://user-images.githubusercontent.com/57693110/95601410-a3df3180-0a10-11eb-955f-ea24134b1eb5.png)

Then i just download it and load on my Geographies component: 

`import React from "react";
import {geoCentroid} from "d3-geo";
import {
  ComposableMap,
  Geographies,
  Geography,
  Marker,
  Annotation,
} from "react-simple-maps";

import geoUrl2 from "./data/guatemala.json";

const geoUrl =
  "https://raw.githubusercontent.com/zcreativelabs/react-simple-maps/master/topojson-maps/world-110m.json";

const Map2 = () => {
  return (
    <div>
      <ComposableMap projectionConfig={{}}>
        <Geographies geography={geoUrl2}>
          {({geographies}) =>
            geographies.map((geo) => (
              <Geography key={geo.rsmKey} geography={geo} />
            ))
          }
        </Geographies>
      </ComposableMap>
    </div>
  );
};

export default Map2;`

In my webpage the map looks : 

![image](https://user-images.githubusercontent.com/57693110/95601605-ee60ae00-0a10-11eb-8a62-e1451a1e8a30.png)

I think is something with the projection, the scale and the rotation. How i know which configuration is the best for my map ?

**Comment by datdotatprotocol** [comment]
You only need to adjust the "Scale" and "center" property of the ComposableMap component.

Something like below:

```
<ComposableMap
        height={550}
        projectionConfig={{
          scale: 1550,
          center: [105, 16]
        }}
        projection="geoMercator"
        data-tip=""
>
  ...
</ComposableMap>
```
