### ISSUE TITLE
Panning in mobile devices breaks after first interaction

### ISSUE THREAD

**Issue by pedrommarquesm** [zcreativelabs/react-simple-maps#244]
Chrome, used in OnePlus 7.

When I zoom (by pinching the device screen), or slide across the map, I am not able to repeat these actions.

This can be reproduced in a browser using the dev tools with mobile device mode one (toggle device toolbar).

https://user-images.githubusercontent.com/54754249/103585687-70ab2200-4edb-11eb-9316-b125a56891e7.mov

Any help with this issue would be cool!

Thanks

**Comment by pedrommarquesm** [comment]
After some debugging, with some luck I found out that by upgrading from react@16.3.1 to @17.0.1 solves this issue (on my project)

I am curious if this would solve the problem with the library itself, since the example in this lib website, featuring zooming/panning is broken.

**Comment by zimrick** [comment]
Updated the example, should be ok now, thanks for flagging this @pedrommarquesm
