### ISSUE TITLE
Restrict map move

### ISSUE THREAD

**Issue by kopach** [zcreativelabs/react-simple-maps#267]
Hi there. Is there any way I could restrict movement of the map? 
See example below. I could move the map out of visible range, and it's hard to get it back to the view. 
![2021-07-12 18 15 55](https://user-images.githubusercontent.com/8749624/125321914-7461aa80-e33d-11eb-9a57-281719ba9c33.gif)

Here is an example of how [HighCharts map](https://www.highcharts.com/demo/maps/all-maps#) does this.

![2021-07-12 18 18 29](https://user-images.githubusercontent.com/8749624/125322088-a83cd000-e33d-11eb-97bd-81a9afd56de2.gif)

Any chance to have something similar with `react-simple-maps`?

**Comment by ratep1** [comment]
Hi, have you tried passing `translateExtent` prop to the `ZoomableGroup`?
[Here is the example](https://codesandbox.io/s/react-simple-maps-constrained-panning-forked-3v0p1?file=/src/MapChart.js)

**Comment by kopach** [comment]
Thanks, that solves the issue. Wasn't aware of this property, sorry about that.
