### ISSUE TITLE
Components should forwardRef

### ISSUE THREAD

**Issue by daedalus28** [zcreativelabs/react-simple-maps#279]
First of all, thanks for this library - it's an excellent tool 🤗 

None of the components in this library currently forward along `ref`s, which makes it hard to use with other libs. An example use case is with the Tooltip from CharkraUI (https://chakra-ui.com/docs/components/overlay/tooltip#usage), which expects children to be able to forward refs along. I've inlined a quick fork of `Geography` in my app to make this work. The diff is pretty trivial - would you be open to a PR adding refs so I don't need to live on a fork?

Here's an example of the diff for `Geography`
<img width="1897" alt="Screen Shot 2022-05-09 at 9 15 03 PM" src="https://user-images.githubusercontent.com/1043503/167541497-dcf5c222-5163-4312-83b7-39622977a0b0.png">

**Comment by zimrick** [comment]
v3 should be forwarding the ref properly now.
