### ISSUE TITLE
Add React ^18 Support

### ISSUE THREAD

**Issue by kennethbigler** [zcreativelabs/react-simple-maps#284]
It would be great to add `^18.0.0` as an option for `react` as a `peerDependency`.

**Comment by zeromero-dev** [comment]
@kennethbigler they merged my pull request which allows the support of React 18.x
You can safely close the issue.

**Comment by enricoros** [comment]
> @kennethbigler they merged my pull request which allows the support of React 18.x You can safely close the issue.

This is great news! But when is this going to be released, or how can we use your code now?

**Comment by zimrick** [comment]
The new v3 beta should support react 18. You can try it out with `npm install react-simple-maps@beta`.
