### ISSUE TITLE
Error when fetching the data of the countries (ERROR 404)

### ISSUE THREAD

**Issue by kirak64** [zcreativelabs/react-simple-maps#289]
I was developing a map to see the countries that visit my website when out of nowhere there was an error in the fetch to obtain the countries.
I saw the examples from the official website https://www.react-simple-maps.io/ and the problem is the same, I think they removed it from the server.
the 404 URL is this:
        GET https://raw.githubusercontent.com/zcreativelabs/react-simple-maps/master/topojson-maps/world-110m.json 404

the error causes the map not to be displayed

**Comment by LOKANADH** [comment]
Even am facing this issue

**Comment by LOKANADH** [comment]
@zimrick Could you please check this?

**Comment by LOKANADH** [comment]
@kirak64 Updating geoUrl to   "https://raw.githubusercontent.com/deldersveld/topojson/master/world-countries.json" worked for me

**Comment by pre-ska** [comment]
> @kirak64 Updating geoUrl to "https://raw.githubusercontent.com/deldersveld/topojson/master/world-countries.json" worked for me

when using this map, there is no properties object for countries in Geography component (in my case, I was using NAME)
is there a way to get country name in that array?

**Comment by zimrick** [comment]
I apologise for this abrupt removal of the files. You should be able to reference the map files from v2 here:
[https://raw.githubusercontent.com/zcreativelabs/react-simple-maps/v2/topojson-maps/world-110m.json](https://raw.githubusercontent.com/zcreativelabs/react-simple-maps/v2/topojson-maps/world-110m.json)

**Comment by zimrick** [comment]
In case you are interested, new links have also been added to different map file sources, which host just map files:
[https://github.com/zcreativelabs/react-simple-maps#map-files](https://github.com/zcreativelabs/react-simple-maps#map-files).

**Comment by pre-ska** [comment]
@zimrick 
thank you very much
for quick answer
