### ISSUE TITLE
viewbox different to width and height

### ISSUE THREAD

**Issue by simon-at-angelsdice** [zcreativelabs/react-simple-maps#29]
Is it possible to have the viewbox to use different values to the svg width and height?

I would like to make the svg be responsive and fill its containers width whilst still ensuring that aspect ratio remains

**Comment by simon-at-angelsdice** [comment]
Please ignore this, i had a rogue style that was causing the issue

**Comment by alexlukelevy** [comment]
Do you have an example of your responsive container? I'm struggling...
