### ISSUE TITLE
GeoJSON results in a Black Screen where the component is placed

### ISSUE THREAD

**Issue by soupmoth** [zcreativelabs/react-simple-maps#290]
New to React so forgive me if this is user error, but I've been stuck on this for 2 days.

My project currently is building an Electoral Map of the UK, representing all 650 constituencies and showing how different election systems, such as PR, AV, and STV can alter the result of elections. To do this, I wish to be able to use the react simple maps framework!

Instead, despite the JSON seemingly being correctly loaded as seen here in the console log
![image](https://user-images.githubusercontent.com/47698102/177668680-3180fb4e-058a-4f02-a839-90bb66c33a81.png)

This is what I get 
![image](https://user-images.githubusercontent.com/47698102/177667429-4131e834-96b0-4d5b-bab8-d1153cde9014.png)

This is my code, where ElectoralMap is the child of another component

![image](https://user-images.githubusercontent.com/47698102/177668416-c49ec423-0c53-4ce6-a9b7-2da29d4dd1a8.png)

The directory.
![image](https://user-images.githubusercontent.com/47698102/177668241-e8f460ae-b7c8-4d3d-a261-3a16344828ca.png)

[JSON I'm using and ElectoralMap.js](https://github.com/zcreativelabs/react-simple-maps/files/9059525/ElectoralMap.zip)

**Comment by zimrick** [comment]
Hi @soupmoth,
Did you try rendering with stroke instead of fill? That way you can see better what is really going on.

```jsx
<Geogrpahy key={geo.rsmKey} geography={geo} fill="none" stroke="#000" />
```

Your react-simple-maps code seems ok and it does seem to be rendering something. The map file could be a bit complex for SVG, but it should still be able to render it. You could try dropping the json in here to see if it works correctly:

[https://mapshaper.org/](https://mapshaper.org/)

**Comment by soupmoth** [comment]
![image](https://user-images.githubusercontent.com/47698102/177787552-7be8ad91-a1b6-4b6a-a25e-ab9dfa9bc881.png)
![image](https://user-images.githubusercontent.com/47698102/177787578-1c313f0e-cc04-4c67-87d8-81d5d7e40c75.png)

Unfortunately still a black screen, and weirder still, the JSON file loads on MapShaper. 

![image](https://user-images.githubusercontent.com/47698102/177788278-8bdbe749-b257-4b74-ab52-527297b85584.png)

I tried simplifying it further to this

![image](https://user-images.githubusercontent.com/47698102/177788133-c0a83580-e481-4dbb-94fc-8285ea9b2781.png)

But now its rendering like this???

![image](https://user-images.githubusercontent.com/47698102/177788187-3dde05d4-189f-462b-95e7-4cfdf807ed2e.png)

**Comment by soupmoth** [comment]
accidnt sorry lol

**Comment by soupmoth** [comment]
> Hi @soupmoth, Did you try rendering with stroke instead of fill? That way you can see better what is really going on.
> 
> ```js
> <Geogrpahy key={geo.rsmKey} geography={geo} fill="none" stroke="#000" />
> ```
> 
> Your react-simple-maps code seems ok and it does seem to be rendering something. The map file could be a bit complex for SVG, but it should still be able to render it. You could try dropping the json in here to see if it works correctly:
> 
> https://mapshaper.org/

went through this line of thinking, spent the day poking around looking for a solution, and couldn't make any progress. The JSON file works in MapShaper and *something* is being rendered as you said, and its clearly more complex then a black square because the patchy black lines.

The only lead I have is it seems all 632 constituencies in this segment of the map are actually being registered, but from what I can tell, are all rendered at the same scale as each other??? So it overlaps in this weird way???

**Comment by zimrick** [comment]
I just noticed that in the screenshot from mapshaper, this seems to be a pre-projected topojson file?
If you load this into mapshaper, open the mapshaper console and run this command:

```
proj wgs84
```

Then export the file as topojson and try to load it into react-simple-maps. Does it work then?
You can project the map in any of the d3-geo projections you want after that (e.g.):

```
<ComposableMap
  width={800}
  height={800}
  projection="geoAlbers"
  projectionConfig={{
    center: [0, 55.4],
    rotate: [4.4, 0, 0],
    parallels: [50, 60],
    scale: 4000,
  }}
>
```

Note that if you are using `ZoomableGroup`, you will have to remove the `center` prop from `projectionConfig` and instead center the map using the `center` prop of the `ZoomableGroup` component.

**Comment by soupmoth** [comment]
![image](https://user-images.githubusercontent.com/47698102/177902611-0dd85f86-108e-4b30-8144-209fe343849d.png)
IT WORKS. THANK YOU SO MUCH. Hopefully this thread helps people in the future, 

(for anyone in the future, the topojson export was VERY important after entering the console command. GeoJSON didn't work even after the corrected projection, but TopoJSON DID!)

this has made my night i can finally sleeeep
