### ISSUE TITLE
Map not displaying with error in console

### ISSUE THREAD

**Issue by stefanocdn** [zcreativelabs/react-simple-maps#3]
Hi, I am using the example in the readme:

```
<ComposableMap style={{ width: "100%" }}>
<ZoomableGroup center={[0,0]}>
   <Geographies
   geographyUrl={ "/public/world-110m.json" }
   >
   {(geographies, projection) => geographies.map(geography => (
   <Geography
   key={ geography.properties.adm0_a3 }
   geography={ geography }
   projection={ projection }
   />
   ))}
   </Geographies>
</ZoomableGroup>
</ComposableMap>
```
The maps is not displayed and I get this error in the console :

```
Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.request.onload (Geographies.js:56)
```
Any idea what I am doing wrong?

**Comment by zimrick** [comment]
Not sure what exact react setup you are using, so a little bit hard for me to help. Can you tell me more about your structure?

I would start by inspecting in Chrome via the network tab, to see what is happening to the ajax call for the topojson file. My guess here is that you are not receiving the topojson on the client. The "<" at position 0 implies that you are instead receiving HTML.

**Comment by stefanocdn** [comment]
You are correct, after inspecting the network, I was receiving html from the ajax call.
Thank you for your help.

**Comment by rkrayovskyy** [comment]
@stefanocdn how did you resolve this issue?

**Comment by joshpitzalis** [comment]
I had a similar problem. I solved it by importing the path at teh top  of my react component
```import geoData from '../../../app/maps/world-50m-with-population.json';
```
and then referencing it in the map
```
<Geographies geography={geoData}>```
