### ISSUE TITLE
How to change text color for country names

### ISSUE THREAD

**Issue by bbolek** [zcreativelabs/react-simple-maps#331]
Hey all,

I want to change color of text for country names. 
![image](https://github.com/zcreativelabs/react-simple-maps/assets/1146456/2dc1f603-5641-469a-b874-07474e350a8c)

```
style={{
            default: {
              fill: '#EEE',
              color: '#FFFF00',
            },
          }}
```

This did not work as it is SVG probably.

Can you help me on this?

Thanks

**Comment by zimrick** [comment]
Usually `fill` should change the text color if applied to a `text` svg tag.
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text

The code above is a little bit too little context to understand what is happening exactly, but it seems that you are trying to apply a fill to the geography and a text color to the label on it. In SVG this would be a separate element though, so the above will not work as intended.

**Comment by bbolek** [comment]
Yes @zimrick, thats is correct. Is there any easy way to change text color of label of country?

Thank you

**Comment by bbolek** [comment]
Ignore it please, I implemented custom Marker, and fixed it.

Thank you

**Comment by EnettyTech** [comment]
> Ignore it please, I implemented custom Marker, and fixed it.
> 
> Thank you

How to show name of country in map? @bbolek
