### ISSUE TITLE
How to get rid of the border rectangle when the country is clicked

### ISSUE THREAD

**Issue by jan-blaska** [zcreativelabs/react-simple-maps#342]
Please, can anyone provide a solution for this? Thank you in advance.

**Comment by jan-blaska** [comment]
I found a solution, for those you will tackle the same as I did, you can add the class to "Geography" component, which you can call for example "country" and then, in CSS, you add this line of code:

`.country:focus {
    display: none;
}`

**Comment by siberry** [comment]
Using `styled-component`, I went with
```
const StyledGeography = styled(Geography)`
  outline: none;
`;
```
