### ISSUE TITLE
Use local json file instead of geographyUrl

### ISSUE THREAD

**Issue by kutyel** [zcreativelabs/react-simple-maps#35]
Hi again @zimrick!

Sorry to bother you again 😅  but I have encountered some problem within our company. The map works perfectly fine but we need now to use a custom topojson map with some codes changed and was trying to use the files inside `topojson-maps` folder on the `node_modules`. We are not using Next.js but some kind of hybrid between an ejected create-react-app and webpack-dev-server config.

When trying to use a local json I get this error:
```sh
Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (<anonymous>)
    at XMLHttpRequest.r.onload (index.js:58)
```

In addition to this do you know of a topojson file like yours `50m-with-data` but with **110** resolution that I could use?

Huge thanks in advance! 😉

**Comment by zimrick** [comment]
RE the use of `geographyPaths`, it's on my todo list to make an example with this, so hopefully I will get around to doing this soon. It's not documented sufficiently at the moment. See #16 .

**Comment by kutyel** [comment]
I managed to do my own file with your instructions and it worked perfectly, thanks so much! 😍 

---

There is still missing the docs for `geographyPaths` but that's OK cause it is in your TODO list 😉
