### ISSUE TITLE
Remove the border whenever I click on a region of the map

### ISSUE THREAD

**Issue by EnettyTech** [zcreativelabs/react-simple-maps#356]
Hello everyone, I want to remove the border whenever I click on a region of the map. How can I do this?
I hope everyone can help me.
<img width="631" alt="Screen Shot 2024-03-27 at 15 10 49" src="https://github.com/zcreativelabs/react-simple-maps/assets/28125294/a353f44b-95bf-47af-9da0-616090f23b66">

**Comment by EnettyTech** [comment]
@Nik-Novak Can you help me?

**Comment by r-ramaraja** [comment]
@EnettyTech 
This is how I did it,
`  <Geography
                    key={geo.rsmKey}
                    geography={geo}
                    fill={isMarkerCounty ? "red" : "#DDD"}
                    onMouseEnter={() => handleMouseEnter(geo)}
                    onMouseLeave={handleMouseLeave}
                    style={{
                      default: {
                        outline: "none",
                      },
                      hover: {
                        outline: "none",
                      },
                      pressed: {
                        outline: "none",
                      },
                    }}
                  />`

**Comment by EnettyTech** [comment]
> @EnettyTech This is how I did it, ` <Geography key={geo.rsmKey} geography={geo} fill={isMarkerCounty ? "red" : "#DDD"} onMouseEnter={() => handleMouseEnter(geo)} onMouseLeave={handleMouseLeave} style={{ default: { outline: "none", }, hover: { outline: "none", }, pressed: { outline: "none", }, }} />`

Worked!! You saved my life!! <3
