### ISSUE TITLE
какой уебок писал эту либку? кому в рот нассать?

### ISSUE THREAD

**Issue by sqlerrorthing** [zcreativelabs/react-simple-maps#363]
сука почему нельзя центрировать эту коченную карту полностью по размерам родительского div контейнера блять?!

**Comment by WhiteOligator** [comment]
ахахахаххахах

**Comment by sqlerrorthing** [comment]
> ахахахаххахах

нихуя не смешно, я все еще ее не центрировал.

**Comment by WhiteOligator** [comment]
<ZoomableGroup
            zoom={position.zoom}
            center={position.coordinates}
            onMoveEnd={handleMoveEnd}
            onMove={handleMove}
            maxZoom={maxZoom}
            minZoom={defaultZoomNormal}
            disablePanning
            filterZoomEvent={(evt: any) => {
              return evt.type !== 'wheel';
            }}
            translateExtent={[
              [-1400, -400],
              [2400, 800],
            ]}
          >

слушай вот этим пропсом можно центрировать, но нужно координаты посчитать
translateExtent={[
              [-1400, -400],
              [2400, 800],
            ]}
и center = [5, 20]; тоже нужно самому прописывать

**Comment by WhiteOligator** [comment]
Вообще библа умерла, давно не обдейтилась куча мерж реквестов никто не заливает
лучше другие варианты поискать https://unovis.dev/docs/maps/TopoJSONMap

**Comment by sqlerrorthing** [comment]
ой спасибки <3
