### ISSUE TITLE
Maps breaking in IE11

### ISSUE THREAD

**Issue by kutyel** [zcreativelabs/react-simple-maps#37]
Hi!

I saw that IE11 supports svg so there should be no problem but I can't see any of the maps in such browser 😱 . Haven't seen either a *compatibility* chart or something in the project, is it supported?

**Comment by zimrick** [comment]
Hmm, strange. It should be supported. Do you have more details about the setup? Do you get any specific error messages? Do the maps on the website show up (e.g. https://www.react-simple-maps.io/basic-map).

**Comment by kutyel** [comment]
That's the thing I tried opening that very same link in IE11 on BrowserStack using a Windows 7 vm and I can't see anything 😟

**Comment by zimrick** [comment]
OK thx for reporting this. Will have a look. I tested with BrowserStack at some point, so maybe something changed.

**Comment by zimrick** [comment]
Just one more thing, are you using a version of react-simple-maps higher than `0.8.2`? I added some fixes there for IE10 at the time (0023129c478f9dcf0902fb435d11590e1bb0a260). I know the website uses a slightly dated version of the library, and the example repos are ready for an upgrade as well. I've been meaning to do this for a while now. If you are using a lower version than `0.8.2` there will be issues with IE10 and IE11 due to the use of `parentElement`, instead of `parentNode`.

**Comment by kutyel** [comment]
`0.8.1` :) I'll upgrade now and try what happens, thank you! 👍

**Comment by kutyel** [comment]
OK so I've just tried it in a IE11 (Win 7) and the map works but its incredibly small, also while zooming (with `react-motion`) it rescales and gets huge, even outside the area it should! Anyone else having this problem? 😟

**Comment by zimrick** [comment]
Hi @kutyel 

So I tried to recreate this, and I think I may have some solutions, at least for some of the issues. In terms of sizing, IE11 seems to have issues with setting the SVG canvas size properly when using responsive styles. What works best for me in general when working with `react-simple-maps`, is to wrap the map in a ratio container. This is in general a good practice to avoid cross-browser/device weirdness. I've had issues with this on mobile devices as well.

Here's how I usually like to set it up:

```js
<div
  style={{
    position: "relative",
    height: 0,
    paddingBottom: "50%",
  }}>
  <div
    style={{
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    }}>
    <ComposableMap
      width={800}
      height={400}
      style={{
        width: "100%",
        height: "100%",
        overflow: "hidden",
      }}>
      <ZoomableGroup>
        <Geographies geography="/static/world-110m.json" disableOptimization>
          {(geos, proj) =>
            geos.map((geo, i) =>
              <Geography
                key={`${geo.properties.ISO_A3}-${i}`}
                cacheId={`${geo.properties.ISO_A3}-${i}`}
                geography={geo}
                projection={proj}
              />
            )
          }
        </Geographies>
      </ZoomableGroup>
    </ComposableMap>
  </div>
</div>
```
Make sure that the ratio is the same between the ratio container and the map width and height, so in this case we get a `2:1` container and the map is `800x400` with a `viewBox` set to `0 0 800 400` and resizes based on the container around it (`100%` width and `100%` height). Hope this makes sense.

This explains the concept behind this a bit better:
https://css-tricks.com/aspect-ratio-boxes/
https://css-tricks.com/snippets/sass/maintain-aspect-ratio-mixin/

This should take care of the map being too small and also the overflow problem. Will check out the `react-motion` stuff as well. Hope this works for you.

Tested with BrowserStack (IE11, Windows7) and `react-simple-maps v.0.10.1`.

**Comment by kutyel** [comment]
This worked like a charm! 🎉 🎉 🎉  Had to play a bit with the `paddingBottom` (59%) but other than that the map works **perfectly** and even with zooming in IE11, huge thanks! ❤️ ❤️ ❤️
