### ISSUE TITLE
Want mousevents to be available on markers.

### ISSUE THREAD

**Issue by mihir478** [zcreativelabs/react-simple-maps#4]
I'm currently using markers to show bubbles on cities on the following world map. I want to be able to have tooltips on markers but it is hard without the event bindings. Want similar event bindings as geography nodes. 

```javascript
<Marker key={idx} marker={{ coordinates: datum.loc }} style={markerStyle}>
          <circle
            cx={0}
            cy={0}
            r={5}
            onMouseMove={(_this, e) => this.showTooltip('New York', 5, e)}
            onMouseLeave={() => this.hideTooltip()}
          />
        </Marker>
```

```javascript
showTooltip(name, value, event) {
      this.setState({ tooltip: {
        ...
        x: event.clientX
        y: event.clientY
      });
  }
```

**Comment by zimrick** [comment]
The events on markers and geographies should behave the same way. I have updated the tooltip gist to show how to add tooltips to markers. Hope that is useful:

https://gist.github.com/zimrick/37c9d38613c192b5dcf485b3f76df42b

**Comment by mihir478** [comment]
@zimrick `this` is not bound correctly in markers. Changing snippet to the following worked.

```javascript
<Marker key={idx} marker={{ coordinates: datum.loc }} style={markerStyle}>
          <circle
            cx={0}
            cy={0}
            r={5}
            onMouseMove={e => this.showTooltip('New York', 5, e)}
            onMouseLeave={() => this.hideTooltip()}
          />
        </Marker>
```

**Comment by zimrick** [comment]
There is a small difference between your code and the one in the gist. I put `onMouseMove` and `onMouseLeave` on the <Marker /> component, not on the circle inside it. The reason you can put SVG inside the marker component is that it gives you the freedom to substitute the circle with any SVG you want to have in there. This opens doors for a lot of fun stuff (e.g. marker icons, labels etc.)

If you take the `onMouseMove` and `onMouseLeave` and put them on the marker you should get the arguments you are looking for. It should behave the same as <Geography /> from that perspective.

**Comment by mihir478** [comment]
Awesome!
