### ISSUE TITLE
Map sometimes not responding to ZoomableGroup center parameter

### ISSUE THREAD

**Issue by LeDanielH** [zcreativelabs/react-simple-maps#40]
Hi, first of all, thanks for this, awesome work!

My issue:
I have managed to set map boundaries for each zoom state 1,2,4,8,16. -> when zoom changes, 
-> it updates current boundaries of the map (hardcoded for each zoom state)
-> which in turn updates center in the ZoomableGroup... so the map can never go out of its boundaries when zooming/panning
I have pan buttons, zoom buttons and it all works fine.

Then I did disablePanning={false}. ZoomableGroup onMoveEnd calls a function which does all of the stuff described above. When I drag the map out of its view, it goes back to its boundaries. Except SOMETIMES it does not. First I thought maybe I update my values incorrectly. But then I checked ZoomableGroup center parameter and it's correct but the map stops responding to it. This only happens with disablePanning={false} and after dragging the map, sometimes. When it stops working, after a third or forth drag/click on map controls button it starts responding again. No error in the console.

This is a screen with map not responding to ZoomableGroup center, see the values at the bottom:
![screen shot 2017-12-06 at 11 01 49](https://user-images.githubusercontent.com/10798542/33656044-2df25146-da75-11e7-8c83-dfdd762ac538.png)

This is a screen with map responding to ZoomableGroup center
![screen shot 2017-12-06 at 11 12 10](https://user-images.githubusercontent.com/10798542/33656509-8e89cad8-da76-11e7-8f9f-be2d44ffcebf.png)

Thank you

**Comment by pronebird** [comment]
Maybe unrelated but I had some weird behavior like this when I had the incorrect width and height set for the `ComposableMap`. Then I hardcoded them and everything seemed to start working correctly.

**Comment by pronebird** [comment]
Exactly the same issue occurred to me today too. Not sure when that's started but changing any prop causes an update to happen.
