### ISSUE TITLE
Tooltip on hover

### ISSUE THREAD

**Issue by koushik72** [zcreativelabs/react-simple-maps#43]
Hi, first of all, I would like to thank all the contributors of this library for their work as I personally find this library to be helpful to my needs. However, I have a request. I don't know if this is something that's already available.
I would like to display a tooltip when hovering on a country. Is this something that already comes right out of the box or can you please suggest if there's any way to achieve it?
Thank you in advance.

**Comment by zimrick** [comment]
Hi @koushik72,

Glad the library is useful to you! :)
The [with-react-tooltip](https://github.com/zcreativelabs/react-simple-maps/tree/master/examples/with-react-tooltip) example should have all that you need for creating simple tooltips on hover using react-tooltip. There's also some useful information in issue #15. In included an example using wsdm-tooltip in there in case you need more control over the markip in the tooltip.

Let me know how it goes.

**Comment by koushik72** [comment]
Hi, thank you very much. I got it to work now. I actually used wsdm-tooltip and took that example that you gave.

**Comment by isabellachen** [comment]
@zimrick The example is no longer in the repo? :( The link above is broken...

**Comment by zimrick** [comment]
You can try using the new tooltip example for `v1` instead:
https://www.react-simple-maps.io/examples/map-chart-with-tooltip/

If you need the old version using react-simple-maps `v0.12.x`, you can still find it on the `v0.12.x` branch:
https://github.com/zcreativelabs/react-simple-maps/tree/v0.12.x/examples/with-react-tooltip
