### ISSUE TITLE
Selecting geographies

### ISSUE THREAD

**Issue by oktalk** [zcreativelabs/react-simple-maps#44]
This is either a feature request or my missunderstanding of the framework.

How can I change the styles on a geography element via click event? E.g.: if a user clicks on a country within my world map, how can I change the CSS styles for that SVG country to show that it has been clicked.

There are already supported styles for hover and pressed, but there is no 'selected' state. Ideally I would love something like this:

```
handleGeographyClick(geography, evt) {
  const svgElement = evt.target;
  svgElement.setAttribute("fill", "red");
}
```
This is a super simplified snippet. I would need something more robust to handle deselecting an element.

**Comment by oktalk** [comment]
I was able to figure it out by following this issue: https://github.com/zcreativelabs/react-simple-maps/issues/8

**Comment by zimrick** [comment]
Hi @oktalk,

Thanks for raising this one. I decided to add an example to the repo, since it's likely that someone else might have the same issue. It's a pretty common use case I think.

https://github.com/zcreativelabs/react-simple-maps/tree/master/examples/select-geographies
