### ISSUE TITLE
Calculate the visible boundary

### ISSUE THREAD

**Issue by pronebird** [zcreativelabs/react-simple-maps#45]
Hi,

I'd like to display a subset of markers for visible boundaries. I basically have a `center` coordinate and then I'd like to extend it to the view boundaries. Is there anything built into `react-simple-maps` that I can use to calculate that?

I figured that I can wrap the `Marker` to extract the `projection` function since `Markers` passes it downwards. I can use it to map the geo coordinate to SVG coordinate space if I get it right.

However I am still not sure how to calculate the visible boundary, maybe you could give me a pointer.

```
const IS_MARKER_IN_VISIBLE_BOUNDARIES = () => {
  // TODO: implement
  return false;
};

const CountryMarker = ({ item, projection, ...otherProps }) => {
  const translation = projection()(item.geometry.coordinates);

  return !IS_MARKER_IN_VISIBLE_BOUNDARIES(translation) ? null : (
    <Marker marker={{ coordinates: item.geometry.coordinates }}
      projection={ projection }
      { ...otherProps }>
      <text fill="rgba(255,255,255,.4)" fontSize="22" textAnchor="middle">
        { item.properties.name }
      </text>
    </Marker>
  );
};

const countryMarkers = countriesJSON.features.map(item => (
  <CountryMarker key={ `a${item.id}` } item={ item } />
));
```

Thanks in advance.

**Comment by pronebird** [comment]
Actually it turned out to be easier than I thought, given the map center coordinate that I already know and projection that either can be picked up from `Marker` or `ComposableMap`. 

```
const center = projection()(mapCenter);
const halfWidth = bounds.width * 0.5 / zoom;
const halfHeight = bounds.height * 0.5 / zoom;
const northWest = [center[0] - halfWidth, center[1] - halfHeight];
const southEast = [center[0] + halfWidth, center[1] + halfHeight];
```

**Comment by stephanemombuleau** [comment]
Hi @pronebird ! I'm looking at doing the same thing, so this issue is a great start for me, thanks! I have a question about the "bounds" element. Which container does this refer to?

**Comment by pronebird** [comment]
@stephanemombuleau basically instead of `bounds`, use the `width` and `height` of the `<ComposableMap>` in pixels.

You can also see the complete implementation I made some time ago for a very simple but interactive world map:

https://github.com/mullvad/mullvadvpn-app/blob/master/gui/src/renderer/components/SvgMap.tsx#L284

**Comment by stephanemombuleau** [comment]
@pronebird Oh great, thank you for sharing that! I'm sure it'll help others as well! :)

**Comment by R1shA3h** [comment]
How can I create visible boundaries(demarcation) over react-simple-maps
