### ISSUE TITLE
albersUsa Projection

### ISSUE THREAD

**Issue by jlichti** [zcreativelabs/react-simple-maps#48]
Thanks for this great library!

I'm using with the albersUsa projection and ran into a small issue I thought I would share. albersUsa  doesn't have a rotate function and ZoomableGroup expects rotate to exist. One possible workaround would be to add a rotate function that doesn't actually rotate.

I'm not using Zooming and Panning for this map so removed ZoomableGroup. ComposableMap seems to expect a single child so my workaround for now was creating a quick child component to pass the projection props along to it's children.

`const GeoGroup = ({ projection, children }) => (
  children.map((child, i) => React.cloneElement(child, { projection, key: i, zoom: 1 }))
);`

**Comment by maganuk** [comment]
I'm having the same issue... cant use AlbersUSA with a Zoomable group

**Comment by zimrick** [comment]
Will have a look at fixing this. There should be an internal override for this.

**Comment by danielmahon** [comment]
I was able to get around this (for now) by overriding the `projection.rotate` function. Took me a bit to figure out the right dummy function but this seems to work and doesn't require modifying your translation. Warning: I haven't tested this too much yet, but I'm not getting any console errors.

```
...
  projection = (width, height) => {
    const albersUsa = d3
      .geoAlbersUsa()
      .scale(1500)
      .translate([width / 2, height / 2]);
    albersUsa.rotate = function rotate(...args) {
      return args.length ? () => [width / 2, height / 2] : [0, 0, 0];
    };
    return albersUsa;
  };
  render() {
    const { zoom } = this.state;
    return (
      <div>
        <button onClick={this.handleZoomIn}>{'Zoom in'}</button>
        <button onClick={this.handleZoomOut}>{'Zoom out'}</button>
        <hr />
        <ComposableMap
          width={1230}
          height={820}
          projection={this.projection}
          style={{
            width: '100%',
            height: 'auto',
          }}
        >
          <ZoomableGroup zoom={zoom}>
            <Geographies geography={mapJSON}>
...
```

**Comment by alexandermeyer** [comment]
@danielmahon That's great! I also get no console errors and adjusting the zoom prop works.

Does changing the center via the center prop work? I'm having issues with the center of the zoom and am wondering if it's related.

**Comment by danielmahon** [comment]
@alexandermeyer I'm working on the same problem now. Can't figure out how to combine the `react-motion` example with the AlbersUsa projection. Zoom seems to work, but not center.

**Comment by zimrick** [comment]
Update: Working on proper support for AlbersUsa... The issue with react-motion could be very tricky. In my prototype I got it to work, but since not all coordinates yield values (note: react-motion + react-simple-maps tweens the coordinate values), there is an issue when animating to Hawaii or Alaska. There is a small animation jump when coordinates are undefined. I can achieve a smoother animation when switching to css transforms and transitions on  `<ZoomableGroup />`. This could be an option on ZoomableGroup.

Here's a gif of the version using CSS transforms and transitions on Chrome:

![albersanimated](https://user-images.githubusercontent.com/7160099/36039192-13663fd8-0dc2-11e8-9c9b-df5d9d14c9be.gif)

**Comment by danielmahon** [comment]
@zimrick Looks great and mesmorizing! FYI I was having the same problem with Albers or AlbersUsa (I only need the lower 48), but maybe Im just not clear on how I need to setup a custom projection to work right with `<ZoomableGroup />`.

**Comment by zimrick** [comment]
If I understand correctly from the d3-geo-projection docs, unless you need the composite AlbersUsa projection (including Hawaii and Alaska), you can use the basic Albers projection, which under the hood seems to be a conicEqualArea projection:
https://github.com/d3/d3-geo/blob/master/src/projection/albers.js

This means that you get rotation etc. out of the box. I tried this earlier and it seems to work with react-simple-maps as is. Let me know if that works for you in this case.

**Comment by danielmahon** [comment]
@zimrick OK, I'm getting close with `d3.geoAlbers()`. But I'm not sure of the correct math to give the right `center` to `<ZoomableGroup />`. It seems as if I have to account for how `geoAlbers` modifies the center and rotation already but Im confused on how to change it... This gets me close but everything is slightly exponentially off when zooming. Since this is more of a guess what should I actually be calculating?

```
projection = () =>
    d3
      .geoAlbers()
      .scale(1400)
      .translate([this.state.width / 2, this.state.height / 2]);
```
```
<ZoomableGroup center={[x + 0.6, y - (96 + 38.7) - height / 2]} zoom={tZoom}>
```

**Comment by danielmahon** [comment]
@zimrick Can you show an example of how you got your demo to work with ZoomableGroup? I can project the US map fine using `geoConicEqualArea` but I still cant figure out where the offset is coming from when I set `center` on ZoomableGroup. Setting center to the coords from a marker do not line up. All seems to work fine with using `mercator` for example.

**Comment by zimrick** [comment]
Yeah, I see what you mean, running into the same problem here. I achieved the above example with a custom ZoomableGroup I am working on to fix the issue. I have to make sure that there are no breaking changes and that all the previously available features work before I can push this to the repo in the next patch.

**Comment by zimrick** [comment]
With [`v0.11.0`](https://github.com/zcreativelabs/react-simple-maps/releases/tag/0.11.0) you should now be able to use the albersUsa projection. Check out the [albersUsa example](https://github.com/zcreativelabs/react-simple-maps/tree/master/examples/albers-usa).

**Comment by marlonmantilla** [comment]
@zimrick link to the example it's broken, I'm getting an issue when using zoom with `projection='geoAlbersUsa'`
