### ISSUE TITLE
New Feature - On load success callback

### ISSUE THREAD

**Issue by erabhimanyu** [zcreativelabs/react-simple-maps#49]
Thanks for this great library !!!

I wish to have a callback once the map is completely initialised. Currently, I am struggling to put a loader since I am not able to detect when the map is successfully rendered and the topojson file is large, resulting in longer wait time before the user gets anything related to map on the screen.

**Comment by zimrick** [comment]
You could try using `onGeographyPathsLoaded`, on `<Geographies />`, which will give you a callback that is triggered once the map renders the geographies.

```jsx
handleLoad = () => {
  console.log("Loaded geographies")
}
...
<Geographies onGeographyPathsLoaded={this.handleLoad}>
  {(geos, proj) =>
    ...
  }
</Geographies>
```

Alternatively you could also load the json yourself, like in the [custom-json-geographyPaths example](https://github.com/zcreativelabs/react-simple-maps/tree/master/examples/custom-json-geographyPaths).

**Comment by erabhimanyu** [comment]
Okay thanks. ononGeographyPathsLoaded works.
Just a clarification needed here, I have to also set `onGeographiesLoaded` in order to get this work. 
As I can see in the implementation:-
```javascript
() => {
            if (!this.props.onGeographiesLoaded) return
            this.props.onGeographyPathsLoaded(String(request.status))
          })
        } else {
          if (!this.props.onGeographiesLoaded) return
          this.props.onGeographyPathsLoaded(String(request.status))
        }
```

**Comment by zimrick** [comment]
Actually, this looks like a mistake. `onGeographiesLoaded` and `onGeographyPathsLoaded` should be the same thing. In the meantime you should be fine by just setting `onGeographiesLoaded={true}` and using `onGeographyPathsLoaded` for the callback, but it is a bit silly, so it should be fixed. Thanks for flagging this.

**Comment by erabhimanyu** [comment]
@zimrick If you are not already investigating it, I can check if it is actually a mistake or there is some logic behind and send a PR.

**Comment by zimrick** [comment]
Sure, that would be great @erabhimanyu.

**Comment by rishavRhombuz** [comment]
In the document , I dont see the onGeographyPathsLoaded property anymore .
