### ISSUE TITLE
Would like panning to stop at outer edges

### ISSUE THREAD

**Issue by mihir478** [zcreativelabs/react-simple-maps#5]
Notice how I can drag the map until there is no data. Can boundary detection please be implemented to avoid this? If you have it already let me know which attribute to pass in where.
<img width="897" alt="screen shot 2017-06-08 at 5 23 04 pm" src="https://user-images.githubusercontent.com/2001420/26951517-694e3712-4c6f-11e7-839c-691b3562dfdc.png">

**Comment by mihir478** [comment]
@zimrick, any ETA on this?

**Comment by zimrick** [comment]
There are a couple of issues with this feature. The way panning works right now, if you prevent it from going out of bounds, you will have issues when setting the center of the map to any place towards the edges of the map.

**Comment by mihir478** [comment]
In that case, (i.e. say you are centering near an edge and the svg dimensions exceed the world map...) maybe you implicitly apply a translate and wrap the world map around along those edges.

**Comment by bondia** [comment]
Do you have any news on that problem?
Are you working on that?
I will need to implement something like that and not sure how to handle it.
Do you thing i will be able to find a way to do that with the current features (zoom and center)?

Thanks!

**Comment by zimrick** [comment]
I have been looking into this issue. It's a bit complex, given how other functionality of the library is handled (setting center and animation), also in terms of how it integrates with other libraries, like `react-motion` and how state is managed. I would really like to see this feature, hence I am also keeping this issue open, but it will likely require some more thinking.

Unfortunately I also don't think you can create anything like this with zoom and center at the moment, as you don't have a way of hooking into panning and zooming events.

**Comment by tcbisthewaytobe** [comment]
Is this something that has managed to be implemented yet? If not is it possible to disable panning, but keep the zoom effects from react-motion?

**Comment by LaikaTheSpaceDog** [comment]
Hello all! I was wondering if anyone has come up with a solution for this yet? I would be eager to hear :)

**Comment by zimrick** [comment]
Hi @LaikaTheSpaceDog,

Does this codesandbox solve the problem you are trying to solve?
https://codesandbox.io/s/react-simple-maps-constrained-panning-3tr6z?file=/src/MapChart.js

Let me know if this helps

**Comment by LaikaTheSpaceDog** [comment]
@zimrick that was a massive help. thanks a lot!
