### ISSUE TITLE
Zooming / Panning broken on firefox

### ISSUE THREAD

**Issue by mihir478** [zcreativelabs/react-simple-maps#6]
On firefox zooming and panning is broken. Note how world map does not expand / shrink or pan.

Unzoomed:
<img width="990" alt="screen shot 2017-06-13 at 1 09 50 pm" src="https://user-images.githubusercontent.com/2001420/27094881-abbcb8e4-5039-11e7-8dc6-71edb4e2a87f.png">

One level of zoom (using 2 as zoom factor for multiply and divide):
<img width="930" alt="screen shot 2017-06-13 at 1 09 54 pm" src="https://user-images.githubusercontent.com/2001420/27094877-a7593bba-5039-11e7-805e-207327687bbd.png">

**Comment by zimrick** [comment]
Thx for flagging this, will investigate.

**Comment by zimrick** [comment]
Just pushed an update that should fix this bug on firefox. Let me know if it works for you.

**Comment by mihir478** [comment]
@zimrick It does! You're the best. I'm going to work on other projects and will come back to maps in few weeks (to add other features and test on other browsers). Take care and keep up the good work!
