### ISSUE TITLE
Geographies componant crash when unmount

### ISSUE THREAD

**Issue by SDanteS** [zcreativelabs/react-simple-maps#61]
Hey guys great lib !
There is a typo mistake in the componentUnmount of Geographies in the function cancelPendingRequest() {
    if (this._xhr) {
      this._xhr.abort()
      thix._xhr = null
    }
  }
can you replace **thix**  with **this**
thanks !

**Comment by this-is-cris** [comment]
Hi @SDanteS,

Thanks for spotting this. I fixed the typo in [v0.10.3](https://github.com/zcreativelabs/react-simple-maps/releases/tag/0.10.3).
