### ISSUE TITLE
Map not getting centered

### ISSUE THREAD

**Issue by iamanoopmk** [zcreativelabs/react-simple-maps#62]
I have a topojson file of US states and am trying to display it inside a div with width 100% and height 500px. The code for the map is as follows

`import React, { Component } from "react"
import {
  ComposableMap,
  ZoomableGroup,
  Geographies,
  Geography,
  Markers,
  Marker,
} from "react-simple-maps"

var map = require("../static/united_states_provinces.json")

class AssetsMap extends Component {

	onMarkerClick(id){
		console.log(id)
		this.props.onMarkerClick(id)
	}

  	render() {
	        var markers = [
	            {markerOffset: [12, 12], coordinates: [-99.5643, 41.4525], name: "name 1"},
				  {markerOffset: [0,12], coordinates: [-94.9560, 45.6259], name: "name 2"},
				  {markerOffset: [-10, 12], coordinates: [-104.063849, 40.861556], name: "name 3"}
	        ]
	        
	    return (
	      <div>
	        <ComposableMap
	          projectionConfig={{ scale: 800 }}
	          style={{
	            width: "100%",
	            height: "400",
	          }}
	          >
	          <ZoomableGroup center={[-130, 33]} disablePanning>
	            <Geographies geography={map}>
	              {(geographies, projection) =>
	                geographies.map((geography, i) =>
	                  true && (
	                    <Geography
	                      key={i}
	                      geography={geography}
	                      projection={projection}
	                      style={{
	                        default: {
	                          fill: "#b1cefb",
	                          stroke: "#FFFFFF",
	                          strokeWidth: 0.75,
	                          outline: "none",
	                        },
	                        hover: {
	                          fill: "#CFD8DC",
	                          stroke: "#FFFFFF",
	                          strokeWidth: 0.75,
	                          outline: "none",
	                        },
	                        pressed: {
	                          fill: "#FF5722",
	                          stroke: "#FFFFFF",
	                          strokeWidth: 0.75,
	                          outline: "none",
	                        },
	                      }}
	                    />
	                  )
	                )
	              }
	            </Geographies>
	            <Markers>
	              {markers.map((marker, i) => (
	                <Marker
	                  key={i}
	                  marker={marker}
	                  onClick = {this.onMarkerClick.bind(this, i)}
	                  style={{
	                    default: { stroke: "#455A64" },
	                    hover: { stroke: "#FF5722" },
	                    pressed: { stroke: "#FF5722" },
	                  }}
	                  >
	                  <g transform="translate(-14, -28)" 
	                  	fill="none" 
	                  	fillRule="evenodd" 
	                  	id="Page-1" 
	                  	stroke="none" 
	                  	strokeWidth="1">
	                  	<sgv-element-here/>
	                  <text
	                    textAnchor="middle"
	                    y={marker.markerOffset[1]}
	                    x={marker.markerOffset[0]}
	                    style={{
	                      fontFamily: "Roboto, sans-serif",
	                      fontSize: "8px",
	                      fill: "#607D8B",
	                      stroke: "none"
	                    }}
	                    >
	                    {marker.name}
	                  </text>
	                </Marker>
	              ))}
	            </Markers>
	          </ZoomableGroup>
	        </ComposableMap>
	      </div>
	    )
  }
}

export default AssetsMap`

It is included in another component as shown below

`<div className="card-block" style={{"padding" : 0}}>
       {<AssetsMap 
            onMarkerClick={this.onMarkerClick.bind(this)}
   </div>`

The problem is that the map is not centered. In my screen it is, but in a screen with different resolution it is not centered. For example in macbook it at the top left corner with half the map clipped while in a windows laptop it is clipped at the bottom. Not sure which property to change to make it centered across all different resolutions. Any help would be greatly appreciated

**Comment by pronebird** [comment]
I think the last time I checked the RSM didn't work properly with `%` dimensions and the width and height must be in pixels.

**Comment by zimrick** [comment]
Hi @iamanoopmk,

I tried to recreate this issue, but for me it also shows up fine. I tried it through browser stack, but so far haven't come across anything weird.

That being said, your problem sounds vaguely familiar in the sense that I had a couple of issues with the center due to how SVG behaves in certain containers. IMO the best way to get good results is to use a container with a fixed ratio. You can achieve this with css on the parent component of `<ComposableMap />` with a trick like this:

```css
.ratio-container {
    position: relative;
    height: 0;
    width: 100%;
    padding-bottom: 50%;
}
.ratio-container-content {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
```

...then you can place your map in this container, in this case with a ratio of 2:1.

```js
const width = 800
const height = width / 2
...
<div className="ratio-container">
    <div className="ratio-container-content">
        <ComposableMap width={width} height={height} style={{ width: "100%", height: "100%" }}>
            ...
        </ComposableMap>
    </div>
</div>
```

The reason I use this method for maps is because sometimes containers get skewed. I once had a problem with `flex-box` and `flex-stretch`, which changed the map container height based on another item that was next to the map container. This resulted in a very weird behavior of the map.

However, if you want a map that has a variable width, and a fixed height, the fixed ratio solution is not very useful.

Let me know if any of this helps.

**Comment by iamanoopmk** [comment]
@zimrick 
Extremely sorry for the late reply.

I tried your solution. While it improved the situation quite a bit but still the map is off on the MacBook compared to my 720p device. I believe it is due to how I set the 'center' property for the ZoomableGroup. I am not sure if that value can be calculated on the fly so that the map can be centered. 

The current behaviour is that the map is shifted to the left but remains in vertically centered.

Thank you for your reply.

**Comment by zimrick** [comment]
I will have another look at this @iamanoopmk . I was looking at the code that you posted above, and what confuses me a little is how you are setting the center of your map. I see that you are passing `[-130, 33]` to the `ZoomableGroup`, but that should probably be the dynamic part? The marker data is passed automatically to the handler, so you can access it in `handleMarkerClick`, which means you get access to your coordinates like so:

```js
handleMarkerClick(markerData) => {
    this.setState({ center: markerData.coordinates })
}
```

```js
<ZoomableGroup center={this.state.center}>
```

```js
markers.map(marker =>
  <Marker marker={marker} onClick={this.handleMarkerClick.bind(this)}>
      { /* Whatever goes into your marker */ }
  </Marker>
)
```

Let me know if this helps.

**Comment by harryprabowo** [comment]
The way I did it was to use a CSS file, and set the width and height of .rsm-svg with the dimensions I want.

**Comment by zimrick** [comment]
Closing this. Centering maps should be easier with v2, since the zooming and panning behaviour is a bit more robust now.
