### ISSUE TITLE
Example Suggestion - D3 USA Choropleth

### ISSUE THREAD

**Issue by easadler** [zcreativelabs/react-simple-maps#63]
This is an awesome library that is currently solving many of my react/d3 woes. It would be really great if you could include a `react-simple-maps` version of the canonical d3 USA Choropleth:[https://bl.ocks.org/mbostock/4060606](https://bl.ocks.org/mbostock/4060606).

I would be happy to add one, but unfortunately I am stuck trying to get [https://d3js.org/us-10m.v1.json](https://d3js.org/us-10m.v1.json) to work with `react-simple-maps`. If this is something you are interested, I would be happy to put up a PR where I am now.

**Comment by easadler** [comment]
The topojson files from [https://github.com/deldersveld/topojson/tree/master/countries/united-states](https://github.com/deldersveld/topojson/tree/master/countries/united-states) seem to work. I guess the topojson from d3 is formatted differently.

**Comment by zimrick** [comment]
Hi @easadler. I am currently working on a proper albersUsa projection implementation in relation to #48, which should be useful for the canonical d3 USA choropleth example. This should be ready very soon, and it will make react-simple-maps significantly more useful for US mapping, but I still have a little bit of testing to do before I am confident enough to push it with the next version.

I will have a look at the formatting of the 10m file, and see what I come up with. Feel free to submit any PRs, I am definitely interested in an example of this.

**Comment by urirahimi** [comment]
Is there an update on this? Would love to have US Chloropleth map

**Comment by zimrick** [comment]
Closing this, but for anyone still looking for USA choropleth examples, check out this:
https://codesandbox.io/s/usa-counties-choropleth-map-quantize-o73pb
