### ISSUE TITLE
Unable to set center with AlbersUsa projection

### ISSUE THREAD

**Issue by alexandermeyer** [zcreativelabs/react-simple-maps#65]
The center prop of ZoomableGroup does not have an effect when using the AlbersUsa projection.

I reproduced this bug on the albers-usa example by adding a center prop, changing the value, and reloading the page, seeing if the map changed position. It had an effect when I switched projections, but I may be misunderstanding how to use albers-usa.

**Comment by zimrick** [comment]
Hi @alexandermeyer 
The albers projection can be tricky when using the center prop, as you can only enter coordinates that are defined by the projection i.e. if you enter a coordinate that is outside the designated area, it will snap back to the center and it will seem like it's not doing anything.

I tried to recreate the issue, but it seems to be working fine here. I used the coordinates of New York to test this: `[-74.0060, 40.7128]`.

Let me know if this works out for you.

**Comment by alexandermeyer** [comment]
Hi @zimrick 
My issue was with albers weirdness with coordinates outside the designated area! Once I calculated centroids and passed those, everything worked as intended. Thanks for the pointer.
