### ISSUE TITLE
Problem on Bubbles map with latitude and longitude coordinates

### ISSUE THREAD

**Issue by luanfonceca** [zcreativelabs/react-simple-maps#67]
Hey folks, i am trying to plot a few countries on a Bubble map, i am using latitude and longitude to mark each country, but they are all plotted wrong, for instance i am using the US with `38` and  `-97`, but the plotted bubble is not in the right place.

<img width="681" alt="screen shot 2018-02-26 at 16 32 35" src="https://user-images.githubusercontent.com/1490875/36690832-4883a4b4-1b12-11e8-9dc5-7bdac1a273e9.png">

Follow my `render` method used on my page:
```
render() {
  const map = {
    center: [0, 20],
    zoom: 1,
  };

  const countries = [{
    name: 'United States',
    latitude_and_longitude: [38, -97],
    total_workers: 10,
  }];

  return (
    <ComposableMap
      projectionConfig={{ scale: 205 }}
      style={{
        width: "100%",
        height: "1024px",
      }}
      >
      <ZoomableGroup center={map.center} zoom={map.zoom}>
        <Geographies geography="/world.json">
          {(geographies, projection) =>
            geographies.map((geography, i) =>
              geography.id !== "ATA" && (
                <Geography
                  key={i}
                  geography={geography}
                  projection={projection}
                />
          ))}
        </Geographies>
        <Markers>
          {
            countries.map((country) => {
              return (
                country.latitude_and_longitude &&
                <Marker
                  key={country.id}
                  marker={{
                    name: country.name,
                    coordinates: country.latitude_and_longitude,
                    population: country.total_workers
                  }}>
                  <circle
                    cx={0}
                    cy={0}
                    r={country.total_workers}
                    fill="rgba(100, 189, 99, 0.8)"
                    stroke="#607D8B"
                    strokeWidth="2"
                    style={{cursor: 'pointer !important'}}
                  />
                </Marker>
              )
            })
          }
        </Markers>
      </ZoomableGroup>
    </ComposableMap>
  );
}
```

**Comment by luanfonceca** [comment]
I think i have figured out, the `Marker` coordinates expected the longitude and latitude instead of latitude and longitude, The reverse order of params?

**Comment by zimrick** [comment]
Hi @luanfonceca 

In react-simple-maps the order for coordinates is `[longitude,latitude]`, so your example should work fine if you switch your coordinates around. Google and d3 use a different order of longitude and latitude to my knowledge, so that can lead to quite some confusion. If you scroll down issue #15 there's some stuff on this, but from what I see this looks like a simple switch situation.

Let me know if this works out for you.

**Comment by zimrick** [comment]
Oh sorry, I just saw you figured it out.

**Comment by luanfonceca** [comment]
Hi @zimrick, i looked over a few issues but not in that one. Thanks for everything. all is working a like a charm now.

<img width="1000" alt="screen shot 2018-02-26 at 16 56 04" src="https://user-images.githubusercontent.com/1490875/36691940-6f35bb94-1b15-11e8-9d16-d2e70a16b7d7.png">

**Comment by rakhimishra** [comment]
`<Marker
                   key={name}
                   coordinates={coordinates}
                   style={markerStyle}
                   }}
                 >
                
                     <g
                       fill="none"
                       stroke="#00A707"
                       strokeWidth="0"
                       strokeLinecap="round"
                       strokeLinejoin="round"
                     >
                       <circle cx="12" cy="10" r="3" fill="#00A707" />
                     </g>
           
                 </Marker>`


<img width="590" alt="Screenshot 2022-04-22 at 12 26 19 AM" src="https://user-images.githubusercontent.com/50749297/164534424-5877f120-c4bd-447b-b8ca-97ab9805ae50.png">
My some of the markers are showing outside of india map.

I am using coordinates : [ long,lat] order
