### ISSUE TITLE
defs not working on ComposableMap

### ISSUE THREAD

**Issue by DaveSauce** [zcreativelabs/react-simple-maps#68]
The map is working great, but I can't get the `defs` to work on `ComposableMap`. On inspection, the defs don't seem to hit the DOM.

```
<ComposableMap
  projectionConfig={{
    scale: props.scale,
    rotation: props.rotation,
    xOffset: 0,
    yOffset: 0,
  }}
  defs={
     <pattern id="diagonalHatch" patternUnits="userSpaceOnUse" width="4" height="4">
       <path d="M-1,1 l2,-2 M0,4 l4,-4 M3,5 l2,-2" style="stroke:black; stroke-width:1" />
     </pattern>
  }
  width={props.mapWidth}
  height={props.mapHeight}
>
 ...
</ComposableMap>
```

I'm not getting any error messages.

**Comment by zimrick** [comment]
Thanks for flagging @DaveSauce , will have a proper look at this. Note if you need patterns for the map asap, you can try putting the pattern in a separate svg on the page. You should still be able to reference it via `id`. This is also a really cool react lib to manage patterns: https://github.com/hshoff/vx/tree/master/packages/vx-pattern

**Comment by DaveSauce** [comment]
Thanks @zimrick! I hadn't thought of that workaround 😄

**Comment by kevinahuber** [comment]
@DaveSauce what version of react-simple-maps are you using? Looks good for me.

**Comment by DaveSauce** [comment]
@kevinahuber Ah, that's it. I was on 0.10.0 - defs works fine on 0.11.0 and 0.11.1. Sorry, I forgot to check that. 

Interestingly, I'm the map loads off center now (actually not visible on screen). I'll start a new issue for that.
