### ISSUE TITLE
Looking for help on a world map by Business Region

### ISSUE THREAD

**Issue by hellofantastic** [zcreativelabs/react-simple-maps#7]
Awesome module!

Wondering if anyone has any insight on a map that is made up of 3 major business regions: Americas, EMEA and APAC. 

So the map looks like this: I used mapchart.net to try and get close but I couldn't get country lines to disappear. 

![screen shot 2017-07-14 at 5 11 11 pm](https://user-images.githubusercontent.com/6655746/28234724-c59055b4-68b7-11e7-9b82-11740bc45f4c.png)

Essentially would like 3 clickable areas by color matching the business regions.
Would I need to start from scratch?

**Comment by zimrick** [comment]
Hi @hellofantastic,

The way I see it, the main issue with this map is the preparation of the topojson file. Rendering it out with `react-simple-maps` and making it clickable/interactive, should not be an issue after that. The process for this would go something like this:

1. Take `world-50m.json` and add zone to country properties

each country should look like this:

```
{
  "arcs": [...], 
  "type":"MultiPolygon",
  "id":"USA",
  "properties": {
    "name":"United States",
    "zone":"Americas"
  }
}
```

You could write a script in node to add the zone property to the `world-50m.json` file, provided you have a data file that references each country's business region by iso3 code. 

2. Use [`topomerge`](https://github.com/topojson/topojson-client#topomerge) to merge the countries into regions

```
$ topomerge -k 'd.properties.zone' zones=units < world-50m.json > world-50m-regions.json
```

There is a [great article written by Mike Bostock on command-line cartography](https://medium.com/@mbostock/command-line-cartography-part-3-1158e4c55a1e), so I would recommend starting there.

**Comment by hellofantastic** [comment]
Sweet!, Thanks @zimrick that insight will do!

**Comment by hellofantastic** [comment]
And in the world-50.json the id is the iso3 code ie; id: TTO -> trinidad and topbago?
the world 50 with data has a bunch of iso fields

**Comment by zimrick** [comment]
Yes, in `world-50m.json` `id` is the iso code. 50m with data has a lot of other information in it (e.g. population, gdp, etc.)

**Comment by hellofantastic** [comment]
So now after running the topomerge line.
```javascript
$ topomerge -k 'd.properties.business_region' business_region=units < world-50m.json > world-50m-regions.json
```

my world-50m-regions.json is identical plus it now has an extra object called business_region with its geometries array now only holding 3 objects 

how to i tell <Geographies .../>  to map over those instead of the units->geometries?
