### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by Taheerj** [zcreativelabs/react-simple-maps#76]
I've got a fairly complex map which is rendering around 3000-4000 SVG Dom Elements at once. The problem is that the performance of most browsers on a fairly good pc starts to degrade with this many elements on the document - it slows down the page and makes everything laggy (e.g. panning, and zooming).

I've tried searching and googling for any way to help me but I can't find anything besides simplifying my map.

Is there any way to optimize the performance of the plugin or anything I can do to make it perform better?

**Comment by krazyjakee** [comment]
I would argue at this point you need to consider using a canvas/webgl solution.

**Comment by kcd71461** [comment]
I tried extending "Geograpy" class for path rendering optimization.
my project needs real-time map update (3~5 geography style update / 1sec) and it works good.

```
/**
 * Created by kimchangduk on 2018-04-25.
 */

import React from 'react';
import PropTypes from 'prop-types';
import deepEqual from 'deep-equal';
import {Geography} from "react-simple-maps";

class LiteGeograpy extends Geography {
    static propTypes = {
        style: PropTypes.object
    };

    shouldComponentUpdate(nextProps) {
        return !deepEqual(this.props.style, nextProps.style);
    }


    render() {
        return (<Geography {...this.props}/>);
    }
}

export default LiteGeograpy;
```
