### ISSUE TITLE
Lines/Line not working

### ISSUE THREAD

**Issue by itelo** [zcreativelabs/react-simple-maps#80]

**Comment by zimrick** [comment]
Can you please give more details about the problem you are encountering? The line component seems to work fine when I test it. Note, it doesn't have default styling, so you need to specify a style to see the line.

```
<Lines>
  <Line
    line={{
      coordinates: {
        start: [0.13, 51.5],
        end: [-74, 40.7],
      }
    }}
    style={{
        default: { stroke: "#000" },
    }}
  />
</Lines>
```

**Comment by itelo** [comment]
sorry, working fine now, but it should be documented

**Comment by zimrick** [comment]
It actually is documented right below the example in `styling and shape`.
https://github.com/zcreativelabs/react-simple-maps#Lines-component
