### ISSUE TITLE
Pressed style doesn't get "unpressed" if mouse leaves the component before mouse up.

### ISSUE THREAD

**Issue by gburtini** [zcreativelabs/react-simple-maps#9]
Here is an animation of me selecting many things on the basic map by releasing my click outside of the bounds of the element: https://cl.ly/1l3w373X0U1c

Reproduction instructions:
- Click an element, do not release.
- Move mouse out of map parent element.
- Release.
- Element stays in "pressed" state, even though we expected it to be unpressed.

**Comment by gburtini** [comment]
![screen recording 2017-08-05 at 06 32 pm](https://user-images.githubusercontent.com/780031/28999842-c73869c2-7a0c-11e7-8c18-05f005775805.gif)

**Comment by zimrick** [comment]
Fixed in v0.6.0. See https://github.com/zcreativelabs/react-simple-maps/commit/33aecff83730528cd506f9cb6727a83262871272
