### ISSUE TITLE
How can I add images to markers?

### ISSUE THREAD

**Issue by mljh92** [zcreativelabs/react-simple-maps#99]
`import myImage from "./icon.png"`
`...`
`<Markers>`
`   ... <Marker ...>`
`      <image src = { myImage }/>`
`      ...`
`   </Marker>`
`</Markers>`
`...`

I want to add an image from a file to point at the marker. Either png or svg. But I can't seem to get it to work. Only element I can add in between the <Marker> are <circle> and <text>

**Comment by zimrick** [comment]
Hmm, strange, this should technically not be a problem. Looking at the code though, I don't think `image` has a `src` attribute in SVG. It uses the `xlink:href` attribute instead. Check out https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image

**Comment by mljh92** [comment]
Hi zimrick! Thanks for the reply! It works now. Apologies that I got mixed up with the src
